package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _Link__PowerV0Claim struct{ x ipld.Link }
type Link__PowerV0Claim = *_Link__PowerV0Claim
func (n Link__PowerV0Claim) Link() ipld.Link {
	return n.x
}
func (_Link__PowerV0Claim__Prototype) FromLink(v ipld.Link) (Link__PowerV0Claim, error) {
	n := _Link__PowerV0Claim{v}
	return &n, nil
}
type _Link__PowerV0Claim__Maybe struct {
	m schema.Maybe
	v Link__PowerV0Claim
}
type MaybeLink__PowerV0Claim = *_Link__PowerV0Claim__Maybe

func (m MaybeLink__PowerV0Claim) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeLink__PowerV0Claim) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeLink__PowerV0Claim) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeLink__PowerV0Claim) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeLink__PowerV0Claim) Must() Link__PowerV0Claim {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var _ ipld.Node = (Link__PowerV0Claim)(&_Link__PowerV0Claim{})
var _ schema.TypedNode = (Link__PowerV0Claim)(&_Link__PowerV0Claim{})
func (Link__PowerV0Claim) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Link
}
func (Link__PowerV0Claim) LookupByString(string) (ipld.Node, error) {
	return mixins.Link{"types.Link__PowerV0Claim"}.LookupByString("")
}
func (Link__PowerV0Claim) LookupByNode(ipld.Node) (ipld.Node, error) {
	return mixins.Link{"types.Link__PowerV0Claim"}.LookupByNode(nil)
}
func (Link__PowerV0Claim) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Link{"types.Link__PowerV0Claim"}.LookupByIndex(0)
}
func (Link__PowerV0Claim) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return mixins.Link{"types.Link__PowerV0Claim"}.LookupBySegment(seg)
}
func (Link__PowerV0Claim) MapIterator() ipld.MapIterator {
	return nil
}
func (Link__PowerV0Claim) ListIterator() ipld.ListIterator {
	return nil
}
func (Link__PowerV0Claim) Length() int {
	return -1
}
func (Link__PowerV0Claim) IsAbsent() bool {
	return false
}
func (Link__PowerV0Claim) IsNull() bool {
	return false
}
func (Link__PowerV0Claim) AsBool() (bool, error) {
	return mixins.Link{"types.Link__PowerV0Claim"}.AsBool()
}
func (Link__PowerV0Claim) AsInt() (int, error) {
	return mixins.Link{"types.Link__PowerV0Claim"}.AsInt()
}
func (Link__PowerV0Claim) AsFloat() (float64, error) {
	return mixins.Link{"types.Link__PowerV0Claim"}.AsFloat()
}
func (Link__PowerV0Claim) AsString() (string, error) {
	return mixins.Link{"types.Link__PowerV0Claim"}.AsString()
}
func (Link__PowerV0Claim) AsBytes() ([]byte, error) {
	return mixins.Link{"types.Link__PowerV0Claim"}.AsBytes()
}
func (n Link__PowerV0Claim) AsLink() (ipld.Link, error) {
	return n.x, nil
}
func (Link__PowerV0Claim) Prototype() ipld.NodePrototype {
	return _Link__PowerV0Claim__Prototype{}
}
type _Link__PowerV0Claim__Prototype struct{}

func (_Link__PowerV0Claim__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _Link__PowerV0Claim__Builder
	nb.Reset()
	return &nb
}
type _Link__PowerV0Claim__Builder struct {
	_Link__PowerV0Claim__Assembler
}
func (nb *_Link__PowerV0Claim__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_Link__PowerV0Claim__Builder) Reset() {
	var w _Link__PowerV0Claim
	var m schema.Maybe
	*nb = _Link__PowerV0Claim__Builder{_Link__PowerV0Claim__Assembler{w: &w, m: &m}}
}
type _Link__PowerV0Claim__Assembler struct {
	w *_Link__PowerV0Claim
	m *schema.Maybe
}

func (na *_Link__PowerV0Claim__Assembler) reset() {}
func (_Link__PowerV0Claim__Assembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.LinkAssembler{"types.Link__PowerV0Claim"}.BeginMap(0)
}
func (_Link__PowerV0Claim__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.LinkAssembler{"types.Link__PowerV0Claim"}.BeginList(0)
}
func (na *_Link__PowerV0Claim__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.LinkAssembler{"types.Link__PowerV0Claim"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	}
	panic("unreachable")
}
func (_Link__PowerV0Claim__Assembler) AssignBool(bool) error {
	return mixins.LinkAssembler{"types.Link__PowerV0Claim"}.AssignBool(false)
}
func (_Link__PowerV0Claim__Assembler) AssignInt(int) error {
	return mixins.LinkAssembler{"types.Link__PowerV0Claim"}.AssignInt(0)
}
func (_Link__PowerV0Claim__Assembler) AssignFloat(float64) error {
	return mixins.LinkAssembler{"types.Link__PowerV0Claim"}.AssignFloat(0)
}
func (_Link__PowerV0Claim__Assembler) AssignString(string) error {
	return mixins.LinkAssembler{"types.Link__PowerV0Claim"}.AssignString("")
}
func (_Link__PowerV0Claim__Assembler) AssignBytes([]byte) error {
	return mixins.LinkAssembler{"types.Link__PowerV0Claim"}.AssignBytes(nil)
}
func (na *_Link__PowerV0Claim__Assembler) AssignLink(v ipld.Link) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	}
	if na.w == nil {
		na.w = &_Link__PowerV0Claim{}
	}
	na.w.x = v
	*na.m = schema.Maybe_Value
	return nil
}
func (na *_Link__PowerV0Claim__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_Link__PowerV0Claim); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v2, err := v.AsLink(); err != nil {
		return err
	} else {
		return na.AssignLink(v2)
	}
}
func (_Link__PowerV0Claim__Assembler) Prototype() ipld.NodePrototype {
	return _Link__PowerV0Claim__Prototype{}
}
func (Link__PowerV0Claim) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n Link__PowerV0Claim) Representation() ipld.Node {
	return (*_Link__PowerV0Claim__Repr)(n)
}
type _Link__PowerV0Claim__Repr = _Link__PowerV0Claim
var _ ipld.Node = &_Link__PowerV0Claim__Repr{}
type _Link__PowerV0Claim__ReprPrototype = _Link__PowerV0Claim__Prototype
type _Link__PowerV0Claim__ReprAssembler = _Link__PowerV0Claim__Assembler
