package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _Link__PowerV2State struct{ x ipld.Link }
type Link__PowerV2State = *_Link__PowerV2State
func (n Link__PowerV2State) Link() ipld.Link {
	return n.x
}
func (_Link__PowerV2State__Prototype) FromLink(v ipld.Link) (Link__PowerV2State, error) {
	n := _Link__PowerV2State{v}
	return &n, nil
}
type _Link__PowerV2State__Maybe struct {
	m schema.Maybe
	v Link__PowerV2State
}
type MaybeLink__PowerV2State = *_Link__PowerV2State__Maybe

func (m MaybeLink__PowerV2State) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeLink__PowerV2State) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeLink__PowerV2State) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeLink__PowerV2State) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeLink__PowerV2State) Must() Link__PowerV2State {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var _ ipld.Node = (Link__PowerV2State)(&_Link__PowerV2State{})
var _ schema.TypedNode = (Link__PowerV2State)(&_Link__PowerV2State{})
func (Link__PowerV2State) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Link
}
func (Link__PowerV2State) LookupByString(string) (ipld.Node, error) {
	return mixins.Link{"types.Link__PowerV2State"}.LookupByString("")
}
func (Link__PowerV2State) LookupByNode(ipld.Node) (ipld.Node, error) {
	return mixins.Link{"types.Link__PowerV2State"}.LookupByNode(nil)
}
func (Link__PowerV2State) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Link{"types.Link__PowerV2State"}.LookupByIndex(0)
}
func (Link__PowerV2State) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return mixins.Link{"types.Link__PowerV2State"}.LookupBySegment(seg)
}
func (Link__PowerV2State) MapIterator() ipld.MapIterator {
	return nil
}
func (Link__PowerV2State) ListIterator() ipld.ListIterator {
	return nil
}
func (Link__PowerV2State) Length() int {
	return -1
}
func (Link__PowerV2State) IsAbsent() bool {
	return false
}
func (Link__PowerV2State) IsNull() bool {
	return false
}
func (Link__PowerV2State) AsBool() (bool, error) {
	return mixins.Link{"types.Link__PowerV2State"}.AsBool()
}
func (Link__PowerV2State) AsInt() (int, error) {
	return mixins.Link{"types.Link__PowerV2State"}.AsInt()
}
func (Link__PowerV2State) AsFloat() (float64, error) {
	return mixins.Link{"types.Link__PowerV2State"}.AsFloat()
}
func (Link__PowerV2State) AsString() (string, error) {
	return mixins.Link{"types.Link__PowerV2State"}.AsString()
}
func (Link__PowerV2State) AsBytes() ([]byte, error) {
	return mixins.Link{"types.Link__PowerV2State"}.AsBytes()
}
func (n Link__PowerV2State) AsLink() (ipld.Link, error) {
	return n.x, nil
}
func (Link__PowerV2State) Prototype() ipld.NodePrototype {
	return _Link__PowerV2State__Prototype{}
}
type _Link__PowerV2State__Prototype struct{}

func (_Link__PowerV2State__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _Link__PowerV2State__Builder
	nb.Reset()
	return &nb
}
type _Link__PowerV2State__Builder struct {
	_Link__PowerV2State__Assembler
}
func (nb *_Link__PowerV2State__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_Link__PowerV2State__Builder) Reset() {
	var w _Link__PowerV2State
	var m schema.Maybe
	*nb = _Link__PowerV2State__Builder{_Link__PowerV2State__Assembler{w: &w, m: &m}}
}
type _Link__PowerV2State__Assembler struct {
	w *_Link__PowerV2State
	m *schema.Maybe
}

func (na *_Link__PowerV2State__Assembler) reset() {}
func (_Link__PowerV2State__Assembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.LinkAssembler{"types.Link__PowerV2State"}.BeginMap(0)
}
func (_Link__PowerV2State__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.LinkAssembler{"types.Link__PowerV2State"}.BeginList(0)
}
func (na *_Link__PowerV2State__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.LinkAssembler{"types.Link__PowerV2State"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	}
	panic("unreachable")
}
func (_Link__PowerV2State__Assembler) AssignBool(bool) error {
	return mixins.LinkAssembler{"types.Link__PowerV2State"}.AssignBool(false)
}
func (_Link__PowerV2State__Assembler) AssignInt(int) error {
	return mixins.LinkAssembler{"types.Link__PowerV2State"}.AssignInt(0)
}
func (_Link__PowerV2State__Assembler) AssignFloat(float64) error {
	return mixins.LinkAssembler{"types.Link__PowerV2State"}.AssignFloat(0)
}
func (_Link__PowerV2State__Assembler) AssignString(string) error {
	return mixins.LinkAssembler{"types.Link__PowerV2State"}.AssignString("")
}
func (_Link__PowerV2State__Assembler) AssignBytes([]byte) error {
	return mixins.LinkAssembler{"types.Link__PowerV2State"}.AssignBytes(nil)
}
func (na *_Link__PowerV2State__Assembler) AssignLink(v ipld.Link) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	}
	if na.w == nil {
		na.w = &_Link__PowerV2State{}
	}
	na.w.x = v
	*na.m = schema.Maybe_Value
	return nil
}
func (na *_Link__PowerV2State__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_Link__PowerV2State); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v2, err := v.AsLink(); err != nil {
		return err
	} else {
		return na.AssignLink(v2)
	}
}
func (_Link__PowerV2State__Assembler) Prototype() ipld.NodePrototype {
	return _Link__PowerV2State__Prototype{}
}
func (Link__PowerV2State) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n Link__PowerV2State) Representation() ipld.Node {
	return (*_Link__PowerV2State__Repr)(n)
}
type _Link__PowerV2State__Repr = _Link__PowerV2State
var _ ipld.Node = &_Link__PowerV2State__Repr{}
type _Link__PowerV2State__ReprPrototype = _Link__PowerV2State__Prototype
type _Link__PowerV2State__ReprAssembler = _Link__PowerV2State__Assembler
