package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _Link__MinerV0Info struct{ x ipld.Link }
type Link__MinerV0Info = *_Link__MinerV0Info
func (n Link__MinerV0Info) Link() ipld.Link {
	return n.x
}
func (_Link__MinerV0Info__Prototype) FromLink(v ipld.Link) (Link__MinerV0Info, error) {
	n := _Link__MinerV0Info{v}
	return &n, nil
}
type _Link__MinerV0Info__Maybe struct {
	m schema.Maybe
	v Link__MinerV0Info
}
type MaybeLink__MinerV0Info = *_Link__MinerV0Info__Maybe

func (m MaybeLink__MinerV0Info) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeLink__MinerV0Info) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeLink__MinerV0Info) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeLink__MinerV0Info) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeLink__MinerV0Info) Must() Link__MinerV0Info {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var _ ipld.Node = (Link__MinerV0Info)(&_Link__MinerV0Info{})
var _ schema.TypedNode = (Link__MinerV0Info)(&_Link__MinerV0Info{})
func (Link__MinerV0Info) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Link
}
func (Link__MinerV0Info) LookupByString(string) (ipld.Node, error) {
	return mixins.Link{"types.Link__MinerV0Info"}.LookupByString("")
}
func (Link__MinerV0Info) LookupByNode(ipld.Node) (ipld.Node, error) {
	return mixins.Link{"types.Link__MinerV0Info"}.LookupByNode(nil)
}
func (Link__MinerV0Info) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Link{"types.Link__MinerV0Info"}.LookupByIndex(0)
}
func (Link__MinerV0Info) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return mixins.Link{"types.Link__MinerV0Info"}.LookupBySegment(seg)
}
func (Link__MinerV0Info) MapIterator() ipld.MapIterator {
	return nil
}
func (Link__MinerV0Info) ListIterator() ipld.ListIterator {
	return nil
}
func (Link__MinerV0Info) Length() int {
	return -1
}
func (Link__MinerV0Info) IsAbsent() bool {
	return false
}
func (Link__MinerV0Info) IsNull() bool {
	return false
}
func (Link__MinerV0Info) AsBool() (bool, error) {
	return mixins.Link{"types.Link__MinerV0Info"}.AsBool()
}
func (Link__MinerV0Info) AsInt() (int, error) {
	return mixins.Link{"types.Link__MinerV0Info"}.AsInt()
}
func (Link__MinerV0Info) AsFloat() (float64, error) {
	return mixins.Link{"types.Link__MinerV0Info"}.AsFloat()
}
func (Link__MinerV0Info) AsString() (string, error) {
	return mixins.Link{"types.Link__MinerV0Info"}.AsString()
}
func (Link__MinerV0Info) AsBytes() ([]byte, error) {
	return mixins.Link{"types.Link__MinerV0Info"}.AsBytes()
}
func (n Link__MinerV0Info) AsLink() (ipld.Link, error) {
	return n.x, nil
}
func (Link__MinerV0Info) Prototype() ipld.NodePrototype {
	return _Link__MinerV0Info__Prototype{}
}
type _Link__MinerV0Info__Prototype struct{}

func (_Link__MinerV0Info__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _Link__MinerV0Info__Builder
	nb.Reset()
	return &nb
}
type _Link__MinerV0Info__Builder struct {
	_Link__MinerV0Info__Assembler
}
func (nb *_Link__MinerV0Info__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_Link__MinerV0Info__Builder) Reset() {
	var w _Link__MinerV0Info
	var m schema.Maybe
	*nb = _Link__MinerV0Info__Builder{_Link__MinerV0Info__Assembler{w: &w, m: &m}}
}
type _Link__MinerV0Info__Assembler struct {
	w *_Link__MinerV0Info
	m *schema.Maybe
}

func (na *_Link__MinerV0Info__Assembler) reset() {}
func (_Link__MinerV0Info__Assembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.LinkAssembler{"types.Link__MinerV0Info"}.BeginMap(0)
}
func (_Link__MinerV0Info__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.LinkAssembler{"types.Link__MinerV0Info"}.BeginList(0)
}
func (na *_Link__MinerV0Info__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.LinkAssembler{"types.Link__MinerV0Info"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	}
	panic("unreachable")
}
func (_Link__MinerV0Info__Assembler) AssignBool(bool) error {
	return mixins.LinkAssembler{"types.Link__MinerV0Info"}.AssignBool(false)
}
func (_Link__MinerV0Info__Assembler) AssignInt(int) error {
	return mixins.LinkAssembler{"types.Link__MinerV0Info"}.AssignInt(0)
}
func (_Link__MinerV0Info__Assembler) AssignFloat(float64) error {
	return mixins.LinkAssembler{"types.Link__MinerV0Info"}.AssignFloat(0)
}
func (_Link__MinerV0Info__Assembler) AssignString(string) error {
	return mixins.LinkAssembler{"types.Link__MinerV0Info"}.AssignString("")
}
func (_Link__MinerV0Info__Assembler) AssignBytes([]byte) error {
	return mixins.LinkAssembler{"types.Link__MinerV0Info"}.AssignBytes(nil)
}
func (na *_Link__MinerV0Info__Assembler) AssignLink(v ipld.Link) error {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	}
	if na.w == nil {
		na.w = &_Link__MinerV0Info{}
	}
	na.w.x = v
	*na.m = schema.Maybe_Value
	return nil
}
func (na *_Link__MinerV0Info__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_Link__MinerV0Info); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v2, err := v.AsLink(); err != nil {
		return err
	} else {
		return na.AssignLink(v2)
	}
}
func (_Link__MinerV0Info__Assembler) Prototype() ipld.NodePrototype {
	return _Link__MinerV0Info__Prototype{}
}
func (Link__MinerV0Info) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (Link__MinerV0Info) LinkTargetNodePrototype() ipld.NodePrototype {
	return Type.Link__MinerV0Info__Repr
}
func (n Link__MinerV0Info) Representation() ipld.Node {
	return (*_Link__MinerV0Info__Repr)(n)
}
type _Link__MinerV0Info__Repr = _Link__MinerV0Info
var _ ipld.Node = &_Link__MinerV0Info__Repr{}
type _Link__MinerV0Info__ReprPrototype = _Link__MinerV0Info__Prototype
type _Link__MinerV0Info__ReprAssembler = _Link__MinerV0Info__Assembler
