package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _LotusMsgMeta struct {
	BlsMessages _Link__ListLotusMessage
	SecpkMessages _Link
}
type LotusMsgMeta = *_LotusMsgMeta

func (n _LotusMsgMeta) FieldBlsMessages()	Link__ListLotusMessage {
	return &n.BlsMessages
}
func (n _LotusMsgMeta) FieldSecpkMessages()	Link {
	return &n.SecpkMessages
}
type _LotusMsgMeta__Maybe struct {
	m schema.Maybe
	v LotusMsgMeta
}
type MaybeLotusMsgMeta = *_LotusMsgMeta__Maybe

func (m MaybeLotusMsgMeta) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeLotusMsgMeta) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeLotusMsgMeta) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeLotusMsgMeta) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeLotusMsgMeta) Must() LotusMsgMeta {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var (
	fieldName__LotusMsgMeta_BlsMessages = _String{"BlsMessages"}
	fieldName__LotusMsgMeta_SecpkMessages = _String{"SecpkMessages"}
)
var _ ipld.Node = (LotusMsgMeta)(&_LotusMsgMeta{})
var _ schema.TypedNode = (LotusMsgMeta)(&_LotusMsgMeta{})
func (LotusMsgMeta) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n LotusMsgMeta) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "BlsMessages":
		return &n.BlsMessages, nil
	case "SecpkMessages":
		return &n.SecpkMessages, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n LotusMsgMeta) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (LotusMsgMeta) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.LotusMsgMeta"}.LookupByIndex(0)
}
func (n LotusMsgMeta) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n LotusMsgMeta) MapIterator() ipld.MapIterator {
	return &_LotusMsgMeta__MapItr{n, 0}
}

type _LotusMsgMeta__MapItr struct {
	n LotusMsgMeta
	idx  int
}

func (itr *_LotusMsgMeta__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 2 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__LotusMsgMeta_BlsMessages
		v = &itr.n.BlsMessages
	case 1:
		k = &fieldName__LotusMsgMeta_SecpkMessages
		v = &itr.n.SecpkMessages
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_LotusMsgMeta__MapItr) Done() bool {
	return itr.idx >= 2
}

func (LotusMsgMeta) ListIterator() ipld.ListIterator {
	return nil
}
func (LotusMsgMeta) Length() int {
	return 2
}
func (LotusMsgMeta) IsAbsent() bool {
	return false
}
func (LotusMsgMeta) IsNull() bool {
	return false
}
func (LotusMsgMeta) AsBool() (bool, error) {
	return mixins.Map{"types.LotusMsgMeta"}.AsBool()
}
func (LotusMsgMeta) AsInt() (int, error) {
	return mixins.Map{"types.LotusMsgMeta"}.AsInt()
}
func (LotusMsgMeta) AsFloat() (float64, error) {
	return mixins.Map{"types.LotusMsgMeta"}.AsFloat()
}
func (LotusMsgMeta) AsString() (string, error) {
	return mixins.Map{"types.LotusMsgMeta"}.AsString()
}
func (LotusMsgMeta) AsBytes() ([]byte, error) {
	return mixins.Map{"types.LotusMsgMeta"}.AsBytes()
}
func (LotusMsgMeta) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.LotusMsgMeta"}.AsLink()
}
func (LotusMsgMeta) Prototype() ipld.NodePrototype {
	return _LotusMsgMeta__Prototype{}
}
type _LotusMsgMeta__Prototype struct{}

func (_LotusMsgMeta__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _LotusMsgMeta__Builder
	nb.Reset()
	return &nb
}
type _LotusMsgMeta__Builder struct {
	_LotusMsgMeta__Assembler
}
func (nb *_LotusMsgMeta__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_LotusMsgMeta__Builder) Reset() {
	var w _LotusMsgMeta
	var m schema.Maybe
	*nb = _LotusMsgMeta__Builder{_LotusMsgMeta__Assembler{w: &w, m: &m}}
}
type _LotusMsgMeta__Assembler struct {
	w *_LotusMsgMeta
	m *schema.Maybe
	state maState
	s int
	f int

	cm schema.Maybe
	ca_BlsMessages _Link__ListLotusMessage__Assembler
	ca_SecpkMessages _Link__Assembler
	}

func (na *_LotusMsgMeta__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_BlsMessages.reset()
	na.ca_SecpkMessages.reset()
}

var (
	fieldBit__LotusMsgMeta_BlsMessages = 1 << 0
	fieldBit__LotusMsgMeta_SecpkMessages = 1 << 1
	fieldBits__LotusMsgMeta_sufficient = 0 + 1 << 0 + 1 << 1
)
func (na *_LotusMsgMeta__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_LotusMsgMeta{}
	}
	return na, nil
}
func (_LotusMsgMeta__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.LotusMsgMeta"}.BeginList(0)
}
func (na *_LotusMsgMeta__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.LotusMsgMeta"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_LotusMsgMeta__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.LotusMsgMeta"}.AssignBool(false)
}
func (_LotusMsgMeta__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.LotusMsgMeta"}.AssignInt(0)
}
func (_LotusMsgMeta__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.LotusMsgMeta"}.AssignFloat(0)
}
func (_LotusMsgMeta__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.LotusMsgMeta"}.AssignString("")
}
func (_LotusMsgMeta__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.LotusMsgMeta"}.AssignBytes(nil)
}
func (_LotusMsgMeta__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.LotusMsgMeta"}.AssignLink(nil)
}
func (na *_LotusMsgMeta__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_LotusMsgMeta); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.LotusMsgMeta", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_LotusMsgMeta__Assembler) Prototype() ipld.NodePrototype {
	return _LotusMsgMeta__Prototype{}
}
func (ma *_LotusMsgMeta__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_BlsMessages.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 1:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_SecpkMessages.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_LotusMsgMeta__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "BlsMessages":
		if ma.s & fieldBit__LotusMsgMeta_BlsMessages != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__LotusMsgMeta_BlsMessages}
		}
		ma.s += fieldBit__LotusMsgMeta_BlsMessages
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_BlsMessages.w = &ma.w.BlsMessages
		ma.ca_BlsMessages.m = &ma.cm
		return &ma.ca_BlsMessages, nil
	case "SecpkMessages":
		if ma.s & fieldBit__LotusMsgMeta_SecpkMessages != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__LotusMsgMeta_SecpkMessages}
		}
		ma.s += fieldBit__LotusMsgMeta_SecpkMessages
		ma.state = maState_midValue
		ma.f = 1
		ma.ca_SecpkMessages.w = &ma.w.SecpkMessages
		ma.ca_SecpkMessages.m = &ma.cm
		return &ma.ca_SecpkMessages, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName:"types.LotusMsgMeta", Key:&_String{k}}
	}
}
func (ma *_LotusMsgMeta__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_LotusMsgMeta__KeyAssembler)(ma)
}
func (ma *_LotusMsgMeta__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_BlsMessages.w = &ma.w.BlsMessages
		ma.ca_BlsMessages.m = &ma.cm
		return &ma.ca_BlsMessages
	case 1:
		ma.ca_SecpkMessages.w = &ma.w.SecpkMessages
		ma.ca_SecpkMessages.m = &ma.cm
		return &ma.ca_SecpkMessages
	default:
		panic("unreachable")
	}
}
func (ma *_LotusMsgMeta__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_LotusMsgMeta__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_LotusMsgMeta__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}
type _LotusMsgMeta__KeyAssembler _LotusMsgMeta__Assembler
func (_LotusMsgMeta__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"types.LotusMsgMeta.KeyAssembler"}.BeginMap(0)
}
func (_LotusMsgMeta__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"types.LotusMsgMeta.KeyAssembler"}.BeginList(0)
}
func (na *_LotusMsgMeta__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"types.LotusMsgMeta.KeyAssembler"}.AssignNull()
}
func (_LotusMsgMeta__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"types.LotusMsgMeta.KeyAssembler"}.AssignBool(false)
}
func (_LotusMsgMeta__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"types.LotusMsgMeta.KeyAssembler"}.AssignInt(0)
}
func (_LotusMsgMeta__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"types.LotusMsgMeta.KeyAssembler"}.AssignFloat(0)
}
func (ka *_LotusMsgMeta__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "BlsMessages":
		if ka.s & fieldBit__LotusMsgMeta_BlsMessages != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__LotusMsgMeta_BlsMessages}
		}
		ka.s += fieldBit__LotusMsgMeta_BlsMessages
		ka.state = maState_expectValue
		ka.f = 0
	case "SecpkMessages":
		if ka.s & fieldBit__LotusMsgMeta_SecpkMessages != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__LotusMsgMeta_SecpkMessages}
		}
		ka.s += fieldBit__LotusMsgMeta_SecpkMessages
		ka.state = maState_expectValue
		ka.f = 1
	default:
		return ipld.ErrInvalidKey{TypeName:"types.LotusMsgMeta", Key:&_String{k}}
	}
	return nil
}
func (_LotusMsgMeta__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"types.LotusMsgMeta.KeyAssembler"}.AssignBytes(nil)
}
func (_LotusMsgMeta__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"types.LotusMsgMeta.KeyAssembler"}.AssignLink(nil)
}
func (ka *_LotusMsgMeta__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_LotusMsgMeta__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (LotusMsgMeta) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n LotusMsgMeta) Representation() ipld.Node {
	return (*_LotusMsgMeta__Repr)(n)
}
type _LotusMsgMeta__Repr _LotusMsgMeta
var _ ipld.Node = &_LotusMsgMeta__Repr{}
func (_LotusMsgMeta__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_LotusMsgMeta__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"types.LotusMsgMeta.Repr"}.LookupByString("")
}
func (n *_LotusMsgMeta__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_LotusMsgMeta__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.BlsMessages.Representation(), nil
	case 1:
		return n.SecpkMessages.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _LotusMsgMeta__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "types.LotusMsgMeta.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_LotusMsgMeta__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_LotusMsgMeta__Repr) ListIterator() ipld.ListIterator {
	return &_LotusMsgMeta__ReprListItr{n, 0}
}

type _LotusMsgMeta__ReprListItr struct {
	n   *_LotusMsgMeta__Repr
	idx int
	
}

func (itr *_LotusMsgMeta__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 2 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.BlsMessages.Representation()
	case 1:
		idx = itr.idx
		v = itr.n.SecpkMessages.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_LotusMsgMeta__ReprListItr) Done() bool {
	return itr.idx >= 2
}

func (rn *_LotusMsgMeta__Repr) Length() int {
	l := 2
	return l
}
func (_LotusMsgMeta__Repr) IsAbsent() bool {
	return false
}
func (_LotusMsgMeta__Repr) IsNull() bool {
	return false
}
func (_LotusMsgMeta__Repr) AsBool() (bool, error) {
	return mixins.List{"types.LotusMsgMeta.Repr"}.AsBool()
}
func (_LotusMsgMeta__Repr) AsInt() (int, error) {
	return mixins.List{"types.LotusMsgMeta.Repr"}.AsInt()
}
func (_LotusMsgMeta__Repr) AsFloat() (float64, error) {
	return mixins.List{"types.LotusMsgMeta.Repr"}.AsFloat()
}
func (_LotusMsgMeta__Repr) AsString() (string, error) {
	return mixins.List{"types.LotusMsgMeta.Repr"}.AsString()
}
func (_LotusMsgMeta__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"types.LotusMsgMeta.Repr"}.AsBytes()
}
func (_LotusMsgMeta__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"types.LotusMsgMeta.Repr"}.AsLink()
}
func (_LotusMsgMeta__Repr) Prototype() ipld.NodePrototype {
	return _LotusMsgMeta__ReprPrototype{}
}
type _LotusMsgMeta__ReprPrototype struct{}

func (_LotusMsgMeta__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _LotusMsgMeta__ReprBuilder
	nb.Reset()
	return &nb
}
type _LotusMsgMeta__ReprBuilder struct {
	_LotusMsgMeta__ReprAssembler
}
func (nb *_LotusMsgMeta__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_LotusMsgMeta__ReprBuilder) Reset() {
	var w _LotusMsgMeta
	var m schema.Maybe
	*nb = _LotusMsgMeta__ReprBuilder{_LotusMsgMeta__ReprAssembler{w: &w, m: &m}}
}
type _LotusMsgMeta__ReprAssembler struct {
	w *_LotusMsgMeta
	m *schema.Maybe
	state laState
	f int

	cm schema.Maybe
	ca_BlsMessages _Link__ListLotusMessage__ReprAssembler
	ca_SecpkMessages _Link__ReprAssembler
	}

func (na *_LotusMsgMeta__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_BlsMessages.reset()
	na.ca_SecpkMessages.reset()
}
func (_LotusMsgMeta__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"types.LotusMsgMeta.Repr"}.BeginMap(0)
}
func (na *_LotusMsgMeta__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_LotusMsgMeta{}
	}
	return na, nil
}
func (na *_LotusMsgMeta__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"types.LotusMsgMeta.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_LotusMsgMeta__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"types.LotusMsgMeta.Repr"}.AssignBool(false)
}
func (_LotusMsgMeta__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"types.LotusMsgMeta.Repr"}.AssignInt(0)
}
func (_LotusMsgMeta__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"types.LotusMsgMeta.Repr"}.AssignFloat(0)
}
func (_LotusMsgMeta__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"types.LotusMsgMeta.Repr"}.AssignString("")
}
func (_LotusMsgMeta__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"types.LotusMsgMeta.Repr"}.AssignBytes(nil)
}
func (_LotusMsgMeta__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"types.LotusMsgMeta.Repr"}.AssignLink(nil)
}
func (na *_LotusMsgMeta__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_LotusMsgMeta); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "types.LotusMsgMeta.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_LotusMsgMeta__ReprAssembler) Prototype() ipld.NodePrototype {
	return _LotusMsgMeta__ReprPrototype{}
}
func (la *_LotusMsgMeta__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 1:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_LotusMsgMeta__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 2 {
		return nil // schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(2)} // FIXME: need an error thunking assembler!  it has returned.  sigh.
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_BlsMessages.w = &la.w.BlsMessages
		la.ca_BlsMessages.m = &la.cm
		return &la.ca_BlsMessages
	case 1:
		la.ca_SecpkMessages.w = &la.w.SecpkMessages
		la.ca_SecpkMessages.m = &la.cm
		return &la.ca_SecpkMessages
	default:
		panic("unreachable")
	}
}
func (la *_LotusMsgMeta__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_LotusMsgMeta__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
