package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _LotusSignedMessage struct {
	Message _LotusMessage
	Signature _Signature
}
type LotusSignedMessage = *_LotusSignedMessage

func (n _LotusSignedMessage) FieldMessage()	LotusMessage {
	return &n.Message
}
func (n _LotusSignedMessage) FieldSignature()	Signature {
	return &n.Signature
}
type _LotusSignedMessage__Maybe struct {
	m schema.Maybe
	v LotusSignedMessage
}
type MaybeLotusSignedMessage = *_LotusSignedMessage__Maybe

func (m MaybeLotusSignedMessage) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeLotusSignedMessage) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeLotusSignedMessage) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeLotusSignedMessage) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeLotusSignedMessage) Must() LotusSignedMessage {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var (
	fieldName__LotusSignedMessage_Message = _String{"Message"}
	fieldName__LotusSignedMessage_Signature = _String{"Signature"}
)
var _ ipld.Node = (LotusSignedMessage)(&_LotusSignedMessage{})
var _ schema.TypedNode = (LotusSignedMessage)(&_LotusSignedMessage{})
func (LotusSignedMessage) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n LotusSignedMessage) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "Message":
		return &n.Message, nil
	case "Signature":
		return &n.Signature, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n LotusSignedMessage) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (LotusSignedMessage) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.LotusSignedMessage"}.LookupByIndex(0)
}
func (n LotusSignedMessage) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n LotusSignedMessage) MapIterator() ipld.MapIterator {
	return &_LotusSignedMessage__MapItr{n, 0}
}

type _LotusSignedMessage__MapItr struct {
	n LotusSignedMessage
	idx  int
}

func (itr *_LotusSignedMessage__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 2 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__LotusSignedMessage_Message
		v = &itr.n.Message
	case 1:
		k = &fieldName__LotusSignedMessage_Signature
		v = &itr.n.Signature
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_LotusSignedMessage__MapItr) Done() bool {
	return itr.idx >= 2
}

func (LotusSignedMessage) ListIterator() ipld.ListIterator {
	return nil
}
func (LotusSignedMessage) Length() int {
	return 2
}
func (LotusSignedMessage) IsAbsent() bool {
	return false
}
func (LotusSignedMessage) IsNull() bool {
	return false
}
func (LotusSignedMessage) AsBool() (bool, error) {
	return mixins.Map{"types.LotusSignedMessage"}.AsBool()
}
func (LotusSignedMessage) AsInt() (int, error) {
	return mixins.Map{"types.LotusSignedMessage"}.AsInt()
}
func (LotusSignedMessage) AsFloat() (float64, error) {
	return mixins.Map{"types.LotusSignedMessage"}.AsFloat()
}
func (LotusSignedMessage) AsString() (string, error) {
	return mixins.Map{"types.LotusSignedMessage"}.AsString()
}
func (LotusSignedMessage) AsBytes() ([]byte, error) {
	return mixins.Map{"types.LotusSignedMessage"}.AsBytes()
}
func (LotusSignedMessage) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.LotusSignedMessage"}.AsLink()
}
func (LotusSignedMessage) Prototype() ipld.NodePrototype {
	return _LotusSignedMessage__Prototype{}
}
type _LotusSignedMessage__Prototype struct{}

func (_LotusSignedMessage__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _LotusSignedMessage__Builder
	nb.Reset()
	return &nb
}
type _LotusSignedMessage__Builder struct {
	_LotusSignedMessage__Assembler
}
func (nb *_LotusSignedMessage__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_LotusSignedMessage__Builder) Reset() {
	var w _LotusSignedMessage
	var m schema.Maybe
	*nb = _LotusSignedMessage__Builder{_LotusSignedMessage__Assembler{w: &w, m: &m}}
}
type _LotusSignedMessage__Assembler struct {
	w *_LotusSignedMessage
	m *schema.Maybe
	state maState
	s int
	f int

	cm schema.Maybe
	ca_Message _LotusMessage__Assembler
	ca_Signature _Signature__Assembler
	}

func (na *_LotusSignedMessage__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_Message.reset()
	na.ca_Signature.reset()
}

var (
	fieldBit__LotusSignedMessage_Message = 1 << 0
	fieldBit__LotusSignedMessage_Signature = 1 << 1
	fieldBits__LotusSignedMessage_sufficient = 0 + 1 << 0 + 1 << 1
)
func (na *_LotusSignedMessage__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_LotusSignedMessage{}
	}
	return na, nil
}
func (_LotusSignedMessage__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.LotusSignedMessage"}.BeginList(0)
}
func (na *_LotusSignedMessage__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.LotusSignedMessage"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_LotusSignedMessage__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.LotusSignedMessage"}.AssignBool(false)
}
func (_LotusSignedMessage__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.LotusSignedMessage"}.AssignInt(0)
}
func (_LotusSignedMessage__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.LotusSignedMessage"}.AssignFloat(0)
}
func (_LotusSignedMessage__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.LotusSignedMessage"}.AssignString("")
}
func (_LotusSignedMessage__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.LotusSignedMessage"}.AssignBytes(nil)
}
func (_LotusSignedMessage__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.LotusSignedMessage"}.AssignLink(nil)
}
func (na *_LotusSignedMessage__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_LotusSignedMessage); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.LotusSignedMessage", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_LotusSignedMessage__Assembler) Prototype() ipld.NodePrototype {
	return _LotusSignedMessage__Prototype{}
}
func (ma *_LotusSignedMessage__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_Message.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 1:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_Signature.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_LotusSignedMessage__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "Message":
		if ma.s & fieldBit__LotusSignedMessage_Message != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__LotusSignedMessage_Message}
		}
		ma.s += fieldBit__LotusSignedMessage_Message
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_Message.w = &ma.w.Message
		ma.ca_Message.m = &ma.cm
		return &ma.ca_Message, nil
	case "Signature":
		if ma.s & fieldBit__LotusSignedMessage_Signature != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__LotusSignedMessage_Signature}
		}
		ma.s += fieldBit__LotusSignedMessage_Signature
		ma.state = maState_midValue
		ma.f = 1
		ma.ca_Signature.w = &ma.w.Signature
		ma.ca_Signature.m = &ma.cm
		return &ma.ca_Signature, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName:"types.LotusSignedMessage", Key:&_String{k}}
	}
}
func (ma *_LotusSignedMessage__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_LotusSignedMessage__KeyAssembler)(ma)
}
func (ma *_LotusSignedMessage__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_Message.w = &ma.w.Message
		ma.ca_Message.m = &ma.cm
		return &ma.ca_Message
	case 1:
		ma.ca_Signature.w = &ma.w.Signature
		ma.ca_Signature.m = &ma.cm
		return &ma.ca_Signature
	default:
		panic("unreachable")
	}
}
func (ma *_LotusSignedMessage__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_LotusSignedMessage__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_LotusSignedMessage__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}
type _LotusSignedMessage__KeyAssembler _LotusSignedMessage__Assembler
func (_LotusSignedMessage__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"types.LotusSignedMessage.KeyAssembler"}.BeginMap(0)
}
func (_LotusSignedMessage__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"types.LotusSignedMessage.KeyAssembler"}.BeginList(0)
}
func (na *_LotusSignedMessage__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"types.LotusSignedMessage.KeyAssembler"}.AssignNull()
}
func (_LotusSignedMessage__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"types.LotusSignedMessage.KeyAssembler"}.AssignBool(false)
}
func (_LotusSignedMessage__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"types.LotusSignedMessage.KeyAssembler"}.AssignInt(0)
}
func (_LotusSignedMessage__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"types.LotusSignedMessage.KeyAssembler"}.AssignFloat(0)
}
func (ka *_LotusSignedMessage__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "Message":
		if ka.s & fieldBit__LotusSignedMessage_Message != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__LotusSignedMessage_Message}
		}
		ka.s += fieldBit__LotusSignedMessage_Message
		ka.state = maState_expectValue
		ka.f = 0
	case "Signature":
		if ka.s & fieldBit__LotusSignedMessage_Signature != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__LotusSignedMessage_Signature}
		}
		ka.s += fieldBit__LotusSignedMessage_Signature
		ka.state = maState_expectValue
		ka.f = 1
	default:
		return ipld.ErrInvalidKey{TypeName:"types.LotusSignedMessage", Key:&_String{k}}
	}
	return nil
}
func (_LotusSignedMessage__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"types.LotusSignedMessage.KeyAssembler"}.AssignBytes(nil)
}
func (_LotusSignedMessage__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"types.LotusSignedMessage.KeyAssembler"}.AssignLink(nil)
}
func (ka *_LotusSignedMessage__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_LotusSignedMessage__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (LotusSignedMessage) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n LotusSignedMessage) Representation() ipld.Node {
	return (*_LotusSignedMessage__Repr)(n)
}
type _LotusSignedMessage__Repr _LotusSignedMessage
var _ ipld.Node = &_LotusSignedMessage__Repr{}
func (_LotusSignedMessage__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_LotusSignedMessage__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"types.LotusSignedMessage.Repr"}.LookupByString("")
}
func (n *_LotusSignedMessage__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_LotusSignedMessage__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.Message.Representation(), nil
	case 1:
		return n.Signature.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _LotusSignedMessage__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "types.LotusSignedMessage.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_LotusSignedMessage__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_LotusSignedMessage__Repr) ListIterator() ipld.ListIterator {
	return &_LotusSignedMessage__ReprListItr{n, 0}
}

type _LotusSignedMessage__ReprListItr struct {
	n   *_LotusSignedMessage__Repr
	idx int
	
}

func (itr *_LotusSignedMessage__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 2 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.Message.Representation()
	case 1:
		idx = itr.idx
		v = itr.n.Signature.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_LotusSignedMessage__ReprListItr) Done() bool {
	return itr.idx >= 2
}

func (rn *_LotusSignedMessage__Repr) Length() int {
	l := 2
	return l
}
func (_LotusSignedMessage__Repr) IsAbsent() bool {
	return false
}
func (_LotusSignedMessage__Repr) IsNull() bool {
	return false
}
func (_LotusSignedMessage__Repr) AsBool() (bool, error) {
	return mixins.List{"types.LotusSignedMessage.Repr"}.AsBool()
}
func (_LotusSignedMessage__Repr) AsInt() (int, error) {
	return mixins.List{"types.LotusSignedMessage.Repr"}.AsInt()
}
func (_LotusSignedMessage__Repr) AsFloat() (float64, error) {
	return mixins.List{"types.LotusSignedMessage.Repr"}.AsFloat()
}
func (_LotusSignedMessage__Repr) AsString() (string, error) {
	return mixins.List{"types.LotusSignedMessage.Repr"}.AsString()
}
func (_LotusSignedMessage__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"types.LotusSignedMessage.Repr"}.AsBytes()
}
func (_LotusSignedMessage__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"types.LotusSignedMessage.Repr"}.AsLink()
}
func (_LotusSignedMessage__Repr) Prototype() ipld.NodePrototype {
	return _LotusSignedMessage__ReprPrototype{}
}
type _LotusSignedMessage__ReprPrototype struct{}

func (_LotusSignedMessage__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _LotusSignedMessage__ReprBuilder
	nb.Reset()
	return &nb
}
type _LotusSignedMessage__ReprBuilder struct {
	_LotusSignedMessage__ReprAssembler
}
func (nb *_LotusSignedMessage__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_LotusSignedMessage__ReprBuilder) Reset() {
	var w _LotusSignedMessage
	var m schema.Maybe
	*nb = _LotusSignedMessage__ReprBuilder{_LotusSignedMessage__ReprAssembler{w: &w, m: &m}}
}
type _LotusSignedMessage__ReprAssembler struct {
	w *_LotusSignedMessage
	m *schema.Maybe
	state laState
	f int

	cm schema.Maybe
	ca_Message _LotusMessage__ReprAssembler
	ca_Signature _Signature__ReprAssembler
	}

func (na *_LotusSignedMessage__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_Message.reset()
	na.ca_Signature.reset()
}
func (_LotusSignedMessage__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"types.LotusSignedMessage.Repr"}.BeginMap(0)
}
func (na *_LotusSignedMessage__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_LotusSignedMessage{}
	}
	return na, nil
}
func (na *_LotusSignedMessage__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"types.LotusSignedMessage.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_LotusSignedMessage__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"types.LotusSignedMessage.Repr"}.AssignBool(false)
}
func (_LotusSignedMessage__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"types.LotusSignedMessage.Repr"}.AssignInt(0)
}
func (_LotusSignedMessage__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"types.LotusSignedMessage.Repr"}.AssignFloat(0)
}
func (_LotusSignedMessage__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"types.LotusSignedMessage.Repr"}.AssignString("")
}
func (_LotusSignedMessage__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"types.LotusSignedMessage.Repr"}.AssignBytes(nil)
}
func (_LotusSignedMessage__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"types.LotusSignedMessage.Repr"}.AssignLink(nil)
}
func (na *_LotusSignedMessage__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_LotusSignedMessage); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "types.LotusSignedMessage.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_LotusSignedMessage__ReprAssembler) Prototype() ipld.NodePrototype {
	return _LotusSignedMessage__ReprPrototype{}
}
func (la *_LotusSignedMessage__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 1:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_LotusSignedMessage__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 2 {
		return nil // schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(2)} // FIXME: need an error thunking assembler!  it has returned.  sigh.
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_Message.w = &la.w.Message
		la.ca_Message.m = &la.cm
		return &la.ca_Message
	case 1:
		la.ca_Signature.w = &la.w.Signature
		la.ca_Signature.m = &la.cm
		return &la.ca_Signature
	default:
		panic("unreachable")
	}
}
func (la *_LotusSignedMessage__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_LotusSignedMessage__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
