package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _LotusStateRoot struct {
	Version _Int
	Actors _Link
	Info _Link
}
type LotusStateRoot = *_LotusStateRoot

func (n _LotusStateRoot) FieldVersion()	Int {
	return &n.Version
}
func (n _LotusStateRoot) FieldActors()	Link {
	return &n.Actors
}
func (n _LotusStateRoot) FieldInfo()	Link {
	return &n.Info
}
type _LotusStateRoot__Maybe struct {
	m schema.Maybe
	v LotusStateRoot
}
type MaybeLotusStateRoot = *_LotusStateRoot__Maybe

func (m MaybeLotusStateRoot) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeLotusStateRoot) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeLotusStateRoot) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeLotusStateRoot) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeLotusStateRoot) Must() LotusStateRoot {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var (
	fieldName__LotusStateRoot_Version = _String{"Version"}
	fieldName__LotusStateRoot_Actors = _String{"Actors"}
	fieldName__LotusStateRoot_Info = _String{"Info"}
)
var _ ipld.Node = (LotusStateRoot)(&_LotusStateRoot{})
var _ schema.TypedNode = (LotusStateRoot)(&_LotusStateRoot{})
func (LotusStateRoot) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n LotusStateRoot) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "Version":
		return &n.Version, nil
	case "Actors":
		return &n.Actors, nil
	case "Info":
		return &n.Info, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n LotusStateRoot) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (LotusStateRoot) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.LotusStateRoot"}.LookupByIndex(0)
}
func (n LotusStateRoot) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n LotusStateRoot) MapIterator() ipld.MapIterator {
	return &_LotusStateRoot__MapItr{n, 0}
}

type _LotusStateRoot__MapItr struct {
	n LotusStateRoot
	idx  int
}

func (itr *_LotusStateRoot__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 3 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__LotusStateRoot_Version
		v = &itr.n.Version
	case 1:
		k = &fieldName__LotusStateRoot_Actors
		v = &itr.n.Actors
	case 2:
		k = &fieldName__LotusStateRoot_Info
		v = &itr.n.Info
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_LotusStateRoot__MapItr) Done() bool {
	return itr.idx >= 3
}

func (LotusStateRoot) ListIterator() ipld.ListIterator {
	return nil
}
func (LotusStateRoot) Length() int {
	return 3
}
func (LotusStateRoot) IsAbsent() bool {
	return false
}
func (LotusStateRoot) IsNull() bool {
	return false
}
func (LotusStateRoot) AsBool() (bool, error) {
	return mixins.Map{"types.LotusStateRoot"}.AsBool()
}
func (LotusStateRoot) AsInt() (int, error) {
	return mixins.Map{"types.LotusStateRoot"}.AsInt()
}
func (LotusStateRoot) AsFloat() (float64, error) {
	return mixins.Map{"types.LotusStateRoot"}.AsFloat()
}
func (LotusStateRoot) AsString() (string, error) {
	return mixins.Map{"types.LotusStateRoot"}.AsString()
}
func (LotusStateRoot) AsBytes() ([]byte, error) {
	return mixins.Map{"types.LotusStateRoot"}.AsBytes()
}
func (LotusStateRoot) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.LotusStateRoot"}.AsLink()
}
func (LotusStateRoot) Prototype() ipld.NodePrototype {
	return _LotusStateRoot__Prototype{}
}
type _LotusStateRoot__Prototype struct{}

func (_LotusStateRoot__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _LotusStateRoot__Builder
	nb.Reset()
	return &nb
}
type _LotusStateRoot__Builder struct {
	_LotusStateRoot__Assembler
}
func (nb *_LotusStateRoot__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_LotusStateRoot__Builder) Reset() {
	var w _LotusStateRoot
	var m schema.Maybe
	*nb = _LotusStateRoot__Builder{_LotusStateRoot__Assembler{w: &w, m: &m}}
}
type _LotusStateRoot__Assembler struct {
	w *_LotusStateRoot
	m *schema.Maybe
	state maState
	s int
	f int

	cm schema.Maybe
	ca_Version _Int__Assembler
	ca_Actors _Link__Assembler
	ca_Info _Link__Assembler
	}

func (na *_LotusStateRoot__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_Version.reset()
	na.ca_Actors.reset()
	na.ca_Info.reset()
}

var (
	fieldBit__LotusStateRoot_Version = 1 << 0
	fieldBit__LotusStateRoot_Actors = 1 << 1
	fieldBit__LotusStateRoot_Info = 1 << 2
	fieldBits__LotusStateRoot_sufficient = 0 + 1 << 0 + 1 << 1 + 1 << 2
)
func (na *_LotusStateRoot__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_LotusStateRoot{}
	}
	return na, nil
}
func (_LotusStateRoot__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.LotusStateRoot"}.BeginList(0)
}
func (na *_LotusStateRoot__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.LotusStateRoot"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_LotusStateRoot__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.LotusStateRoot"}.AssignBool(false)
}
func (_LotusStateRoot__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.LotusStateRoot"}.AssignInt(0)
}
func (_LotusStateRoot__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.LotusStateRoot"}.AssignFloat(0)
}
func (_LotusStateRoot__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.LotusStateRoot"}.AssignString("")
}
func (_LotusStateRoot__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.LotusStateRoot"}.AssignBytes(nil)
}
func (_LotusStateRoot__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.LotusStateRoot"}.AssignLink(nil)
}
func (na *_LotusStateRoot__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_LotusStateRoot); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.LotusStateRoot", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_LotusStateRoot__Assembler) Prototype() ipld.NodePrototype {
	return _LotusStateRoot__Prototype{}
}
func (ma *_LotusStateRoot__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_Version.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 1:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_Actors.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 2:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_Info.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_LotusStateRoot__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "Version":
		if ma.s & fieldBit__LotusStateRoot_Version != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__LotusStateRoot_Version}
		}
		ma.s += fieldBit__LotusStateRoot_Version
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_Version.w = &ma.w.Version
		ma.ca_Version.m = &ma.cm
		return &ma.ca_Version, nil
	case "Actors":
		if ma.s & fieldBit__LotusStateRoot_Actors != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__LotusStateRoot_Actors}
		}
		ma.s += fieldBit__LotusStateRoot_Actors
		ma.state = maState_midValue
		ma.f = 1
		ma.ca_Actors.w = &ma.w.Actors
		ma.ca_Actors.m = &ma.cm
		return &ma.ca_Actors, nil
	case "Info":
		if ma.s & fieldBit__LotusStateRoot_Info != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__LotusStateRoot_Info}
		}
		ma.s += fieldBit__LotusStateRoot_Info
		ma.state = maState_midValue
		ma.f = 2
		ma.ca_Info.w = &ma.w.Info
		ma.ca_Info.m = &ma.cm
		return &ma.ca_Info, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName:"types.LotusStateRoot", Key:&_String{k}}
	}
}
func (ma *_LotusStateRoot__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_LotusStateRoot__KeyAssembler)(ma)
}
func (ma *_LotusStateRoot__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_Version.w = &ma.w.Version
		ma.ca_Version.m = &ma.cm
		return &ma.ca_Version
	case 1:
		ma.ca_Actors.w = &ma.w.Actors
		ma.ca_Actors.m = &ma.cm
		return &ma.ca_Actors
	case 2:
		ma.ca_Info.w = &ma.w.Info
		ma.ca_Info.m = &ma.cm
		return &ma.ca_Info
	default:
		panic("unreachable")
	}
}
func (ma *_LotusStateRoot__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_LotusStateRoot__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_LotusStateRoot__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}
type _LotusStateRoot__KeyAssembler _LotusStateRoot__Assembler
func (_LotusStateRoot__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"types.LotusStateRoot.KeyAssembler"}.BeginMap(0)
}
func (_LotusStateRoot__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"types.LotusStateRoot.KeyAssembler"}.BeginList(0)
}
func (na *_LotusStateRoot__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"types.LotusStateRoot.KeyAssembler"}.AssignNull()
}
func (_LotusStateRoot__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"types.LotusStateRoot.KeyAssembler"}.AssignBool(false)
}
func (_LotusStateRoot__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"types.LotusStateRoot.KeyAssembler"}.AssignInt(0)
}
func (_LotusStateRoot__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"types.LotusStateRoot.KeyAssembler"}.AssignFloat(0)
}
func (ka *_LotusStateRoot__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "Version":
		if ka.s & fieldBit__LotusStateRoot_Version != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__LotusStateRoot_Version}
		}
		ka.s += fieldBit__LotusStateRoot_Version
		ka.state = maState_expectValue
		ka.f = 0
	case "Actors":
		if ka.s & fieldBit__LotusStateRoot_Actors != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__LotusStateRoot_Actors}
		}
		ka.s += fieldBit__LotusStateRoot_Actors
		ka.state = maState_expectValue
		ka.f = 1
	case "Info":
		if ka.s & fieldBit__LotusStateRoot_Info != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__LotusStateRoot_Info}
		}
		ka.s += fieldBit__LotusStateRoot_Info
		ka.state = maState_expectValue
		ka.f = 2
	default:
		return ipld.ErrInvalidKey{TypeName:"types.LotusStateRoot", Key:&_String{k}}
	}
	return nil
}
func (_LotusStateRoot__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"types.LotusStateRoot.KeyAssembler"}.AssignBytes(nil)
}
func (_LotusStateRoot__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"types.LotusStateRoot.KeyAssembler"}.AssignLink(nil)
}
func (ka *_LotusStateRoot__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_LotusStateRoot__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (LotusStateRoot) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n LotusStateRoot) Representation() ipld.Node {
	return (*_LotusStateRoot__Repr)(n)
}
type _LotusStateRoot__Repr _LotusStateRoot
var _ ipld.Node = &_LotusStateRoot__Repr{}
func (_LotusStateRoot__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_LotusStateRoot__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"types.LotusStateRoot.Repr"}.LookupByString("")
}
func (n *_LotusStateRoot__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_LotusStateRoot__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.Version.Representation(), nil
	case 1:
		return n.Actors.Representation(), nil
	case 2:
		return n.Info.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _LotusStateRoot__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "types.LotusStateRoot.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_LotusStateRoot__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_LotusStateRoot__Repr) ListIterator() ipld.ListIterator {
	return &_LotusStateRoot__ReprListItr{n, 0}
}

type _LotusStateRoot__ReprListItr struct {
	n   *_LotusStateRoot__Repr
	idx int
	
}

func (itr *_LotusStateRoot__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 3 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.Version.Representation()
	case 1:
		idx = itr.idx
		v = itr.n.Actors.Representation()
	case 2:
		idx = itr.idx
		v = itr.n.Info.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_LotusStateRoot__ReprListItr) Done() bool {
	return itr.idx >= 3
}

func (rn *_LotusStateRoot__Repr) Length() int {
	l := 3
	return l
}
func (_LotusStateRoot__Repr) IsAbsent() bool {
	return false
}
func (_LotusStateRoot__Repr) IsNull() bool {
	return false
}
func (_LotusStateRoot__Repr) AsBool() (bool, error) {
	return mixins.List{"types.LotusStateRoot.Repr"}.AsBool()
}
func (_LotusStateRoot__Repr) AsInt() (int, error) {
	return mixins.List{"types.LotusStateRoot.Repr"}.AsInt()
}
func (_LotusStateRoot__Repr) AsFloat() (float64, error) {
	return mixins.List{"types.LotusStateRoot.Repr"}.AsFloat()
}
func (_LotusStateRoot__Repr) AsString() (string, error) {
	return mixins.List{"types.LotusStateRoot.Repr"}.AsString()
}
func (_LotusStateRoot__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"types.LotusStateRoot.Repr"}.AsBytes()
}
func (_LotusStateRoot__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"types.LotusStateRoot.Repr"}.AsLink()
}
func (_LotusStateRoot__Repr) Prototype() ipld.NodePrototype {
	return _LotusStateRoot__ReprPrototype{}
}
type _LotusStateRoot__ReprPrototype struct{}

func (_LotusStateRoot__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _LotusStateRoot__ReprBuilder
	nb.Reset()
	return &nb
}
type _LotusStateRoot__ReprBuilder struct {
	_LotusStateRoot__ReprAssembler
}
func (nb *_LotusStateRoot__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_LotusStateRoot__ReprBuilder) Reset() {
	var w _LotusStateRoot
	var m schema.Maybe
	*nb = _LotusStateRoot__ReprBuilder{_LotusStateRoot__ReprAssembler{w: &w, m: &m}}
}
type _LotusStateRoot__ReprAssembler struct {
	w *_LotusStateRoot
	m *schema.Maybe
	state laState
	f int

	cm schema.Maybe
	ca_Version _Int__ReprAssembler
	ca_Actors _Link__ReprAssembler
	ca_Info _Link__ReprAssembler
	}

func (na *_LotusStateRoot__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_Version.reset()
	na.ca_Actors.reset()
	na.ca_Info.reset()
}
func (_LotusStateRoot__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"types.LotusStateRoot.Repr"}.BeginMap(0)
}
func (na *_LotusStateRoot__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_LotusStateRoot{}
	}
	return na, nil
}
func (na *_LotusStateRoot__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"types.LotusStateRoot.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_LotusStateRoot__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"types.LotusStateRoot.Repr"}.AssignBool(false)
}
func (_LotusStateRoot__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"types.LotusStateRoot.Repr"}.AssignInt(0)
}
func (_LotusStateRoot__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"types.LotusStateRoot.Repr"}.AssignFloat(0)
}
func (_LotusStateRoot__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"types.LotusStateRoot.Repr"}.AssignString("")
}
func (_LotusStateRoot__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"types.LotusStateRoot.Repr"}.AssignBytes(nil)
}
func (_LotusStateRoot__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"types.LotusStateRoot.Repr"}.AssignLink(nil)
}
func (na *_LotusStateRoot__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_LotusStateRoot); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "types.LotusStateRoot.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_LotusStateRoot__ReprAssembler) Prototype() ipld.NodePrototype {
	return _LotusStateRoot__ReprPrototype{}
}
func (la *_LotusStateRoot__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 1:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 2:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_LotusStateRoot__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 3 {
		return nil // schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(3)} // FIXME: need an error thunking assembler!  it has returned.  sigh.
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_Version.w = &la.w.Version
		la.ca_Version.m = &la.cm
		return &la.ca_Version
	case 1:
		la.ca_Actors.w = &la.w.Actors
		la.ca_Actors.m = &la.cm
		return &la.ca_Actors
	case 2:
		la.ca_Info.w = &la.w.Info
		la.ca_Info.m = &la.cm
		return &la.ca_Info
	default:
		panic("unreachable")
	}
}
func (la *_LotusStateRoot__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_LotusStateRoot__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
