package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _Map__MultisigV0Transaction struct {
	m map[_String]*_MultisigV0Transaction
	t []_Map__MultisigV0Transaction__entry
}
type Map__MultisigV0Transaction = *_Map__MultisigV0Transaction
type _Map__MultisigV0Transaction__entry struct {
	k _String
	v _MultisigV0Transaction
}
func (n *_Map__MultisigV0Transaction) LookupMaybe(k String) MaybeMultisigV0Transaction {
	v, ok := n.m[*k]
	if !ok {
		return &_Map__MultisigV0Transaction__valueAbsent
	}
	return &_MultisigV0Transaction__Maybe{
		m: schema.Maybe_Value,
		v: v,
	}
}

var _Map__MultisigV0Transaction__valueAbsent = _MultisigV0Transaction__Maybe{m:schema.Maybe_Absent}

// TODO generate also a plain Lookup method that doesn't box and alloc if this type contains non-nullable values!
type _Map__MultisigV0Transaction__Maybe struct {
	m schema.Maybe
	v Map__MultisigV0Transaction
}
type MaybeMap__MultisigV0Transaction = *_Map__MultisigV0Transaction__Maybe

func (m MaybeMap__MultisigV0Transaction) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeMap__MultisigV0Transaction) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeMap__MultisigV0Transaction) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeMap__MultisigV0Transaction) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeMap__MultisigV0Transaction) Must() Map__MultisigV0Transaction {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var _ ipld.Node = (Map__MultisigV0Transaction)(&_Map__MultisigV0Transaction{})
var _ schema.TypedNode = (Map__MultisigV0Transaction)(&_Map__MultisigV0Transaction{})
func (Map__MultisigV0Transaction) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n Map__MultisigV0Transaction) LookupByString(k string) (ipld.Node, error) {
	var k2 _String
	if err := (_String__Prototype{}).fromString(&k2, k); err != nil {
		return nil, err // TODO wrap in some kind of ErrInvalidKey
	}
	v, exists := n.m[k2]
	if !exists {
		return nil, ipld.ErrNotExists{ipld.PathSegmentOfString(k)}
	}
	return v, nil
}
func (n Map__MultisigV0Transaction) LookupByNode(k ipld.Node) (ipld.Node, error) {
	k2, ok := k.(String)
	if !ok {
		panic("todo invalid key type error")
		// 'ipld.ErrInvalidKey{TypeName:"types.Map__MultisigV0Transaction", Key:&_String{k}}' doesn't quite cut it: need room to explain the type, and it's not guaranteed k can be turned into a string at all
	}
	v, exists := n.m[*k2]
	if !exists {
		return nil, ipld.ErrNotExists{ipld.PathSegmentOfString(k2.String())}
	}
	return v, nil
}
func (Map__MultisigV0Transaction) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction"}.LookupByIndex(0)
}
func (n Map__MultisigV0Transaction) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n Map__MultisigV0Transaction) MapIterator() ipld.MapIterator {
	return &_Map__MultisigV0Transaction__MapItr{n, 0}
}

type _Map__MultisigV0Transaction__MapItr struct {
	n Map__MultisigV0Transaction
	idx  int
}

func (itr *_Map__MultisigV0Transaction__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= len(itr.n.t) {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	x := &itr.n.t[itr.idx]
	k = &x.k
	v = &x.v
	itr.idx++
	return
}
func (itr *_Map__MultisigV0Transaction__MapItr) Done() bool {
	return itr.idx >= len(itr.n.t)
}

func (Map__MultisigV0Transaction) ListIterator() ipld.ListIterator {
	return nil
}
func (n Map__MultisigV0Transaction) Length() int {
	return len(n.t)
}
func (Map__MultisigV0Transaction) IsAbsent() bool {
	return false
}
func (Map__MultisigV0Transaction) IsNull() bool {
	return false
}
func (Map__MultisigV0Transaction) AsBool() (bool, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction"}.AsBool()
}
func (Map__MultisigV0Transaction) AsInt() (int, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction"}.AsInt()
}
func (Map__MultisigV0Transaction) AsFloat() (float64, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction"}.AsFloat()
}
func (Map__MultisigV0Transaction) AsString() (string, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction"}.AsString()
}
func (Map__MultisigV0Transaction) AsBytes() ([]byte, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction"}.AsBytes()
}
func (Map__MultisigV0Transaction) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction"}.AsLink()
}
func (Map__MultisigV0Transaction) Prototype() ipld.NodePrototype {
	return _Map__MultisigV0Transaction__Prototype{}
}
type _Map__MultisigV0Transaction__Prototype struct{}

func (_Map__MultisigV0Transaction__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _Map__MultisigV0Transaction__Builder
	nb.Reset()
	return &nb
}
type _Map__MultisigV0Transaction__Builder struct {
	_Map__MultisigV0Transaction__Assembler
}
func (nb *_Map__MultisigV0Transaction__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_Map__MultisigV0Transaction__Builder) Reset() {
	var w _Map__MultisigV0Transaction
	var m schema.Maybe
	*nb = _Map__MultisigV0Transaction__Builder{_Map__MultisigV0Transaction__Assembler{w: &w, m: &m}}
}
type _Map__MultisigV0Transaction__Assembler struct {
	w *_Map__MultisigV0Transaction
	m *schema.Maybe
	state maState

	cm schema.Maybe
	ka _String__Assembler
	va _MultisigV0Transaction__Assembler
}

func (na *_Map__MultisigV0Transaction__Assembler) reset() {
	na.state = maState_initial
	na.ka.reset()
	na.va.reset()
}
func (na *_Map__MultisigV0Transaction__Assembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if sizeHint < 0 {
		sizeHint = 0
	}
	if na.w == nil {
		na.w = &_Map__MultisigV0Transaction{}
	}
	na.w.m = make(map[_String]*_MultisigV0Transaction, sizeHint)
	na.w.t = make([]_Map__MultisigV0Transaction__entry, 0, sizeHint)
	return na, nil
}
func (_Map__MultisigV0Transaction__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction"}.BeginList(0)
}
func (na *_Map__MultisigV0Transaction__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.Map__MultisigV0Transaction"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_Map__MultisigV0Transaction__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction"}.AssignBool(false)
}
func (_Map__MultisigV0Transaction__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction"}.AssignInt(0)
}
func (_Map__MultisigV0Transaction__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction"}.AssignFloat(0)
}
func (_Map__MultisigV0Transaction__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction"}.AssignString("")
}
func (_Map__MultisigV0Transaction__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction"}.AssignBytes(nil)
}
func (_Map__MultisigV0Transaction__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction"}.AssignLink(nil)
}
func (na *_Map__MultisigV0Transaction__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_Map__MultisigV0Transaction); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.Map__MultisigV0Transaction", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_Map__MultisigV0Transaction__Assembler) Prototype() ipld.NodePrototype {
	return _Map__MultisigV0Transaction__Prototype{}
}
func (ma *_Map__MultisigV0Transaction__Assembler) keyFinishTidy() bool {
	switch ma.cm {
	case schema.Maybe_Value:
		ma.ka.w = nil
		tz := &ma.w.t[len(ma.w.t)-1]
		ma.cm = schema.Maybe_Absent
		ma.state = maState_expectValue
		ma.w.m[tz.k] = &tz.v
		ma.va.w = &tz.v
		ma.va.m = &ma.cm
		ma.ka.reset()
		return true
	default:
		return false
	}
}
func (ma *_Map__MultisigV0Transaction__Assembler) valueFinishTidy() bool {
	switch ma.cm {
	case schema.Maybe_Value:
		ma.va.w = nil
		ma.cm = schema.Maybe_Absent
		ma.state = maState_initial
		ma.va.reset()
		return true
	default:
		return false
	}
}
func (ma *_Map__MultisigV0Transaction__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}

	var k2 _String
	if err := (_String__Prototype{}).fromString(&k2, k); err != nil {
		return nil, err // TODO wrap in some kind of ErrInvalidKey
	}
	if _, exists := ma.w.m[k2]; exists {
		return nil, ipld.ErrRepeatedMapKey{&k2}
	}
	ma.w.t = append(ma.w.t, _Map__MultisigV0Transaction__entry{k: k2})
	tz := &ma.w.t[len(ma.w.t)-1]
	ma.state = maState_midValue

	ma.w.m[k2] = &tz.v
	ma.va.w = &tz.v
	ma.va.m = &ma.cm
	return &ma.va, nil
}
func (ma *_Map__MultisigV0Transaction__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.w.t = append(ma.w.t, _Map__MultisigV0Transaction__entry{})
	ma.state = maState_midKey
	ma.ka.m = &ma.cm
	ma.ka.w = &ma.w.t[len(ma.w.t)-1].k
	return &ma.ka
}
func (ma *_Map__MultisigV0Transaction__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		if !ma.keyFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
		} // if tidy success: carry on
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	return &ma.va
}
func (ma *_Map__MultisigV0Transaction__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_Map__MultisigV0Transaction__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_Map__MultisigV0Transaction__Assembler) ValuePrototype(_ string) ipld.NodePrototype {
	return _MultisigV0Transaction__Prototype{}
}
func (Map__MultisigV0Transaction) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n Map__MultisigV0Transaction) Representation() ipld.Node {
	return (*_Map__MultisigV0Transaction__Repr)(n)
}
type _Map__MultisigV0Transaction__Repr _Map__MultisigV0Transaction
var _ ipld.Node = &_Map__MultisigV0Transaction__Repr{}
func (_Map__MultisigV0Transaction__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (nr *_Map__MultisigV0Transaction__Repr) LookupByString(k string) (ipld.Node, error) {
	v, err := (Map__MultisigV0Transaction)(nr).LookupByString(k)
	if err != nil || v == ipld.Null {
		return v, err
	}
	return v.(MultisigV0Transaction).Representation(), nil
}
func (nr *_Map__MultisigV0Transaction__Repr) LookupByNode(k ipld.Node) (ipld.Node, error) {
	v, err := (Map__MultisigV0Transaction)(nr).LookupByNode(k)
	if err != nil || v == ipld.Null {
		return v, err
	}
	return v.(MultisigV0Transaction).Representation(), nil
}
func (_Map__MultisigV0Transaction__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction.Repr"}.LookupByIndex(0)
}
func (n _Map__MultisigV0Transaction__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (nr *_Map__MultisigV0Transaction__Repr) MapIterator() ipld.MapIterator {
	return &_Map__MultisigV0Transaction__ReprMapItr{(Map__MultisigV0Transaction)(nr), 0}
}

type _Map__MultisigV0Transaction__ReprMapItr _Map__MultisigV0Transaction__MapItr

func (itr *_Map__MultisigV0Transaction__ReprMapItr) Next() (k ipld.Node, v ipld.Node, err error) {
	k, v, err = (*_Map__MultisigV0Transaction__MapItr)(itr).Next()
	if err != nil || v == ipld.Null {
		return
	}
	return k, v.(MultisigV0Transaction).Representation(), nil
}
func (itr *_Map__MultisigV0Transaction__ReprMapItr) Done() bool {
	return (*_Map__MultisigV0Transaction__MapItr)(itr).Done()
}

func (_Map__MultisigV0Transaction__Repr) ListIterator() ipld.ListIterator {
	return nil
}
func (rn *_Map__MultisigV0Transaction__Repr) Length() int {
	return len(rn.t)
}
func (_Map__MultisigV0Transaction__Repr) IsAbsent() bool {
	return false
}
func (_Map__MultisigV0Transaction__Repr) IsNull() bool {
	return false
}
func (_Map__MultisigV0Transaction__Repr) AsBool() (bool, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction.Repr"}.AsBool()
}
func (_Map__MultisigV0Transaction__Repr) AsInt() (int, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction.Repr"}.AsInt()
}
func (_Map__MultisigV0Transaction__Repr) AsFloat() (float64, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction.Repr"}.AsFloat()
}
func (_Map__MultisigV0Transaction__Repr) AsString() (string, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction.Repr"}.AsString()
}
func (_Map__MultisigV0Transaction__Repr) AsBytes() ([]byte, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction.Repr"}.AsBytes()
}
func (_Map__MultisigV0Transaction__Repr) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.Map__MultisigV0Transaction.Repr"}.AsLink()
}
func (_Map__MultisigV0Transaction__Repr) Prototype() ipld.NodePrototype {
	return _Map__MultisigV0Transaction__ReprPrototype{}
}
type _Map__MultisigV0Transaction__ReprPrototype struct{}

func (_Map__MultisigV0Transaction__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _Map__MultisigV0Transaction__ReprBuilder
	nb.Reset()
	return &nb
}
type _Map__MultisigV0Transaction__ReprBuilder struct {
	_Map__MultisigV0Transaction__ReprAssembler
}
func (nb *_Map__MultisigV0Transaction__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_Map__MultisigV0Transaction__ReprBuilder) Reset() {
	var w _Map__MultisigV0Transaction
	var m schema.Maybe
	*nb = _Map__MultisigV0Transaction__ReprBuilder{_Map__MultisigV0Transaction__ReprAssembler{w: &w, m: &m}}
}
type _Map__MultisigV0Transaction__ReprAssembler struct {
	w *_Map__MultisigV0Transaction
	m *schema.Maybe
	state maState

	cm schema.Maybe
	ka _String__ReprAssembler
	va _MultisigV0Transaction__ReprAssembler
}

func (na *_Map__MultisigV0Transaction__ReprAssembler) reset() {
	na.state = maState_initial
	na.ka.reset()
	na.va.reset()
}
func (na *_Map__MultisigV0Transaction__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if sizeHint < 0 {
		sizeHint = 0
	}
	if na.w == nil {
		na.w = &_Map__MultisigV0Transaction{}
	}
	na.w.m = make(map[_String]*_MultisigV0Transaction, sizeHint)
	na.w.t = make([]_Map__MultisigV0Transaction__entry, 0, sizeHint)
	return na, nil
}
func (_Map__MultisigV0Transaction__ReprAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction.Repr"}.BeginList(0)
}
func (na *_Map__MultisigV0Transaction__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.Map__MultisigV0Transaction.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_Map__MultisigV0Transaction__ReprAssembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction.Repr"}.AssignBool(false)
}
func (_Map__MultisigV0Transaction__ReprAssembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction.Repr"}.AssignInt(0)
}
func (_Map__MultisigV0Transaction__ReprAssembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction.Repr"}.AssignFloat(0)
}
func (_Map__MultisigV0Transaction__ReprAssembler) AssignString(string) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction.Repr"}.AssignString("")
}
func (_Map__MultisigV0Transaction__ReprAssembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction.Repr"}.AssignBytes(nil)
}
func (_Map__MultisigV0Transaction__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.Map__MultisigV0Transaction.Repr"}.AssignLink(nil)
}
func (na *_Map__MultisigV0Transaction__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_Map__MultisigV0Transaction); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.Map__MultisigV0Transaction.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_Map__MultisigV0Transaction__ReprAssembler) Prototype() ipld.NodePrototype {
	return _Map__MultisigV0Transaction__ReprPrototype{}
}
func (ma *_Map__MultisigV0Transaction__ReprAssembler) keyFinishTidy() bool {
	switch ma.cm {
	case schema.Maybe_Value:
		ma.ka.w = nil
		tz := &ma.w.t[len(ma.w.t)-1]
		ma.cm = schema.Maybe_Absent
		ma.state = maState_expectValue
		ma.w.m[tz.k] = &tz.v
		ma.va.w = &tz.v
		ma.va.m = &ma.cm
		ma.ka.reset()
		return true
	default:
		return false
	}
}
func (ma *_Map__MultisigV0Transaction__ReprAssembler) valueFinishTidy() bool {
	switch ma.cm {
	case schema.Maybe_Value:
		ma.va.w = nil
		ma.cm = schema.Maybe_Absent
		ma.state = maState_initial
		ma.va.reset()
		return true
	default:
		return false
	}
}
func (ma *_Map__MultisigV0Transaction__ReprAssembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}

	var k2 _String
	if err := (_String__ReprPrototype{}).fromString(&k2, k); err != nil {
		return nil, err // TODO wrap in some kind of ErrInvalidKey
	}
	if _, exists := ma.w.m[k2]; exists {
		return nil, ipld.ErrRepeatedMapKey{&k2}
	}
	ma.w.t = append(ma.w.t, _Map__MultisigV0Transaction__entry{k: k2})
	tz := &ma.w.t[len(ma.w.t)-1]
	ma.state = maState_midValue

	ma.w.m[k2] = &tz.v
	ma.va.w = &tz.v
	ma.va.m = &ma.cm
	return &ma.va, nil
}
func (ma *_Map__MultisigV0Transaction__ReprAssembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.w.t = append(ma.w.t, _Map__MultisigV0Transaction__entry{})
	ma.state = maState_midKey
	ma.ka.m = &ma.cm
	ma.ka.w = &ma.w.t[len(ma.w.t)-1].k
	return &ma.ka
}
func (ma *_Map__MultisigV0Transaction__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		if !ma.keyFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
		} // if tidy success: carry on
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	return &ma.va
}
func (ma *_Map__MultisigV0Transaction__ReprAssembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_Map__MultisigV0Transaction__ReprAssembler) KeyPrototype() ipld.NodePrototype {
	return _String__ReprPrototype{}
}
func (ma *_Map__MultisigV0Transaction__ReprAssembler) ValuePrototype(_ string) ipld.NodePrototype {
	return _MultisigV0Transaction__ReprPrototype{}
}
