package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _MessageParamsMinerExtendSectorExpiration struct {
	Extension _List__MinerExpirationExtend
}
type MessageParamsMinerExtendSectorExpiration = *_MessageParamsMinerExtendSectorExpiration

func (n _MessageParamsMinerExtendSectorExpiration) FieldExtension()	List__MinerExpirationExtend {
	return &n.Extension
}
type _MessageParamsMinerExtendSectorExpiration__Maybe struct {
	m schema.Maybe
	v MessageParamsMinerExtendSectorExpiration
}
type MaybeMessageParamsMinerExtendSectorExpiration = *_MessageParamsMinerExtendSectorExpiration__Maybe

func (m MaybeMessageParamsMinerExtendSectorExpiration) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeMessageParamsMinerExtendSectorExpiration) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeMessageParamsMinerExtendSectorExpiration) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeMessageParamsMinerExtendSectorExpiration) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeMessageParamsMinerExtendSectorExpiration) Must() MessageParamsMinerExtendSectorExpiration {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var (
	fieldName__MessageParamsMinerExtendSectorExpiration_Extension = _String{"Extension"}
)
var _ ipld.Node = (MessageParamsMinerExtendSectorExpiration)(&_MessageParamsMinerExtendSectorExpiration{})
var _ schema.TypedNode = (MessageParamsMinerExtendSectorExpiration)(&_MessageParamsMinerExtendSectorExpiration{})
func (MessageParamsMinerExtendSectorExpiration) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n MessageParamsMinerExtendSectorExpiration) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "Extension":
		return &n.Extension, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n MessageParamsMinerExtendSectorExpiration) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (MessageParamsMinerExtendSectorExpiration) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.MessageParamsMinerExtendSectorExpiration"}.LookupByIndex(0)
}
func (n MessageParamsMinerExtendSectorExpiration) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n MessageParamsMinerExtendSectorExpiration) MapIterator() ipld.MapIterator {
	return &_MessageParamsMinerExtendSectorExpiration__MapItr{n, 0}
}

type _MessageParamsMinerExtendSectorExpiration__MapItr struct {
	n MessageParamsMinerExtendSectorExpiration
	idx  int
}

func (itr *_MessageParamsMinerExtendSectorExpiration__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 1 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__MessageParamsMinerExtendSectorExpiration_Extension
		v = &itr.n.Extension
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MessageParamsMinerExtendSectorExpiration__MapItr) Done() bool {
	return itr.idx >= 1
}

func (MessageParamsMinerExtendSectorExpiration) ListIterator() ipld.ListIterator {
	return nil
}
func (MessageParamsMinerExtendSectorExpiration) Length() int {
	return 1
}
func (MessageParamsMinerExtendSectorExpiration) IsAbsent() bool {
	return false
}
func (MessageParamsMinerExtendSectorExpiration) IsNull() bool {
	return false
}
func (MessageParamsMinerExtendSectorExpiration) AsBool() (bool, error) {
	return mixins.Map{"types.MessageParamsMinerExtendSectorExpiration"}.AsBool()
}
func (MessageParamsMinerExtendSectorExpiration) AsInt() (int, error) {
	return mixins.Map{"types.MessageParamsMinerExtendSectorExpiration"}.AsInt()
}
func (MessageParamsMinerExtendSectorExpiration) AsFloat() (float64, error) {
	return mixins.Map{"types.MessageParamsMinerExtendSectorExpiration"}.AsFloat()
}
func (MessageParamsMinerExtendSectorExpiration) AsString() (string, error) {
	return mixins.Map{"types.MessageParamsMinerExtendSectorExpiration"}.AsString()
}
func (MessageParamsMinerExtendSectorExpiration) AsBytes() ([]byte, error) {
	return mixins.Map{"types.MessageParamsMinerExtendSectorExpiration"}.AsBytes()
}
func (MessageParamsMinerExtendSectorExpiration) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.MessageParamsMinerExtendSectorExpiration"}.AsLink()
}
func (MessageParamsMinerExtendSectorExpiration) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerExtendSectorExpiration__Prototype{}
}
type _MessageParamsMinerExtendSectorExpiration__Prototype struct{}

func (_MessageParamsMinerExtendSectorExpiration__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _MessageParamsMinerExtendSectorExpiration__Builder
	nb.Reset()
	return &nb
}
type _MessageParamsMinerExtendSectorExpiration__Builder struct {
	_MessageParamsMinerExtendSectorExpiration__Assembler
}
func (nb *_MessageParamsMinerExtendSectorExpiration__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MessageParamsMinerExtendSectorExpiration__Builder) Reset() {
	var w _MessageParamsMinerExtendSectorExpiration
	var m schema.Maybe
	*nb = _MessageParamsMinerExtendSectorExpiration__Builder{_MessageParamsMinerExtendSectorExpiration__Assembler{w: &w, m: &m}}
}
type _MessageParamsMinerExtendSectorExpiration__Assembler struct {
	w *_MessageParamsMinerExtendSectorExpiration
	m *schema.Maybe
	state maState
	s int
	f int

	cm schema.Maybe
	ca_Extension _List__MinerExpirationExtend__Assembler
	}

func (na *_MessageParamsMinerExtendSectorExpiration__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_Extension.reset()
}

var (
	fieldBit__MessageParamsMinerExtendSectorExpiration_Extension = 1 << 0
	fieldBits__MessageParamsMinerExtendSectorExpiration_sufficient = 0 + 1 << 0
)
func (na *_MessageParamsMinerExtendSectorExpiration__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MessageParamsMinerExtendSectorExpiration{}
	}
	return na, nil
}
func (_MessageParamsMinerExtendSectorExpiration__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.MessageParamsMinerExtendSectorExpiration"}.BeginList(0)
}
func (na *_MessageParamsMinerExtendSectorExpiration__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.MessageParamsMinerExtendSectorExpiration"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MessageParamsMinerExtendSectorExpiration__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.MessageParamsMinerExtendSectorExpiration"}.AssignBool(false)
}
func (_MessageParamsMinerExtendSectorExpiration__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.MessageParamsMinerExtendSectorExpiration"}.AssignInt(0)
}
func (_MessageParamsMinerExtendSectorExpiration__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.MessageParamsMinerExtendSectorExpiration"}.AssignFloat(0)
}
func (_MessageParamsMinerExtendSectorExpiration__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.MessageParamsMinerExtendSectorExpiration"}.AssignString("")
}
func (_MessageParamsMinerExtendSectorExpiration__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.MessageParamsMinerExtendSectorExpiration"}.AssignBytes(nil)
}
func (_MessageParamsMinerExtendSectorExpiration__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.MessageParamsMinerExtendSectorExpiration"}.AssignLink(nil)
}
func (na *_MessageParamsMinerExtendSectorExpiration__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MessageParamsMinerExtendSectorExpiration); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.MessageParamsMinerExtendSectorExpiration", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MessageParamsMinerExtendSectorExpiration__Assembler) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerExtendSectorExpiration__Prototype{}
}
func (ma *_MessageParamsMinerExtendSectorExpiration__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_Extension.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_MessageParamsMinerExtendSectorExpiration__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "Extension":
		if ma.s & fieldBit__MessageParamsMinerExtendSectorExpiration_Extension != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MessageParamsMinerExtendSectorExpiration_Extension}
		}
		ma.s += fieldBit__MessageParamsMinerExtendSectorExpiration_Extension
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_Extension.w = &ma.w.Extension
		ma.ca_Extension.m = &ma.cm
		return &ma.ca_Extension, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName:"types.MessageParamsMinerExtendSectorExpiration", Key:&_String{k}}
	}
}
func (ma *_MessageParamsMinerExtendSectorExpiration__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_MessageParamsMinerExtendSectorExpiration__KeyAssembler)(ma)
}
func (ma *_MessageParamsMinerExtendSectorExpiration__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_Extension.w = &ma.w.Extension
		ma.ca_Extension.m = &ma.cm
		return &ma.ca_Extension
	default:
		panic("unreachable")
	}
}
func (ma *_MessageParamsMinerExtendSectorExpiration__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_MessageParamsMinerExtendSectorExpiration__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_MessageParamsMinerExtendSectorExpiration__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}
type _MessageParamsMinerExtendSectorExpiration__KeyAssembler _MessageParamsMinerExtendSectorExpiration__Assembler
func (_MessageParamsMinerExtendSectorExpiration__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"types.MessageParamsMinerExtendSectorExpiration.KeyAssembler"}.BeginMap(0)
}
func (_MessageParamsMinerExtendSectorExpiration__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"types.MessageParamsMinerExtendSectorExpiration.KeyAssembler"}.BeginList(0)
}
func (na *_MessageParamsMinerExtendSectorExpiration__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"types.MessageParamsMinerExtendSectorExpiration.KeyAssembler"}.AssignNull()
}
func (_MessageParamsMinerExtendSectorExpiration__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"types.MessageParamsMinerExtendSectorExpiration.KeyAssembler"}.AssignBool(false)
}
func (_MessageParamsMinerExtendSectorExpiration__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"types.MessageParamsMinerExtendSectorExpiration.KeyAssembler"}.AssignInt(0)
}
func (_MessageParamsMinerExtendSectorExpiration__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"types.MessageParamsMinerExtendSectorExpiration.KeyAssembler"}.AssignFloat(0)
}
func (ka *_MessageParamsMinerExtendSectorExpiration__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "Extension":
		if ka.s & fieldBit__MessageParamsMinerExtendSectorExpiration_Extension != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MessageParamsMinerExtendSectorExpiration_Extension}
		}
		ka.s += fieldBit__MessageParamsMinerExtendSectorExpiration_Extension
		ka.state = maState_expectValue
		ka.f = 0
	default:
		return ipld.ErrInvalidKey{TypeName:"types.MessageParamsMinerExtendSectorExpiration", Key:&_String{k}}
	}
	return nil
}
func (_MessageParamsMinerExtendSectorExpiration__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"types.MessageParamsMinerExtendSectorExpiration.KeyAssembler"}.AssignBytes(nil)
}
func (_MessageParamsMinerExtendSectorExpiration__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"types.MessageParamsMinerExtendSectorExpiration.KeyAssembler"}.AssignLink(nil)
}
func (ka *_MessageParamsMinerExtendSectorExpiration__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_MessageParamsMinerExtendSectorExpiration__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (MessageParamsMinerExtendSectorExpiration) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n MessageParamsMinerExtendSectorExpiration) Representation() ipld.Node {
	return (*_MessageParamsMinerExtendSectorExpiration__Repr)(n)
}
type _MessageParamsMinerExtendSectorExpiration__Repr _MessageParamsMinerExtendSectorExpiration
var _ ipld.Node = &_MessageParamsMinerExtendSectorExpiration__Repr{}
func (_MessageParamsMinerExtendSectorExpiration__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.LookupByString("")
}
func (n *_MessageParamsMinerExtendSectorExpiration__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_MessageParamsMinerExtendSectorExpiration__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.Extension.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _MessageParamsMinerExtendSectorExpiration__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "types.MessageParamsMinerExtendSectorExpiration.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_MessageParamsMinerExtendSectorExpiration__Repr) ListIterator() ipld.ListIterator {
	return &_MessageParamsMinerExtendSectorExpiration__ReprListItr{n, 0}
}

type _MessageParamsMinerExtendSectorExpiration__ReprListItr struct {
	n   *_MessageParamsMinerExtendSectorExpiration__Repr
	idx int
	
}

func (itr *_MessageParamsMinerExtendSectorExpiration__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 1 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.Extension.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MessageParamsMinerExtendSectorExpiration__ReprListItr) Done() bool {
	return itr.idx >= 1
}

func (rn *_MessageParamsMinerExtendSectorExpiration__Repr) Length() int {
	l := 1
	return l
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) IsAbsent() bool {
	return false
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) IsNull() bool {
	return false
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) AsBool() (bool, error) {
	return mixins.List{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AsBool()
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) AsInt() (int, error) {
	return mixins.List{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AsInt()
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) AsFloat() (float64, error) {
	return mixins.List{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AsFloat()
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) AsString() (string, error) {
	return mixins.List{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AsString()
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AsBytes()
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AsLink()
}
func (_MessageParamsMinerExtendSectorExpiration__Repr) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerExtendSectorExpiration__ReprPrototype{}
}
type _MessageParamsMinerExtendSectorExpiration__ReprPrototype struct{}

func (_MessageParamsMinerExtendSectorExpiration__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _MessageParamsMinerExtendSectorExpiration__ReprBuilder
	nb.Reset()
	return &nb
}
type _MessageParamsMinerExtendSectorExpiration__ReprBuilder struct {
	_MessageParamsMinerExtendSectorExpiration__ReprAssembler
}
func (nb *_MessageParamsMinerExtendSectorExpiration__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MessageParamsMinerExtendSectorExpiration__ReprBuilder) Reset() {
	var w _MessageParamsMinerExtendSectorExpiration
	var m schema.Maybe
	*nb = _MessageParamsMinerExtendSectorExpiration__ReprBuilder{_MessageParamsMinerExtendSectorExpiration__ReprAssembler{w: &w, m: &m}}
}
type _MessageParamsMinerExtendSectorExpiration__ReprAssembler struct {
	w *_MessageParamsMinerExtendSectorExpiration
	m *schema.Maybe
	state laState
	f int

	cm schema.Maybe
	ca_Extension _List__MinerExpirationExtend__ReprAssembler
	}

func (na *_MessageParamsMinerExtendSectorExpiration__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_Extension.reset()
}
func (_MessageParamsMinerExtendSectorExpiration__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.BeginMap(0)
}
func (na *_MessageParamsMinerExtendSectorExpiration__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MessageParamsMinerExtendSectorExpiration{}
	}
	return na, nil
}
func (na *_MessageParamsMinerExtendSectorExpiration__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"types.MessageParamsMinerExtendSectorExpiration.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MessageParamsMinerExtendSectorExpiration__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AssignBool(false)
}
func (_MessageParamsMinerExtendSectorExpiration__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AssignInt(0)
}
func (_MessageParamsMinerExtendSectorExpiration__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AssignFloat(0)
}
func (_MessageParamsMinerExtendSectorExpiration__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AssignString("")
}
func (_MessageParamsMinerExtendSectorExpiration__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AssignBytes(nil)
}
func (_MessageParamsMinerExtendSectorExpiration__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"types.MessageParamsMinerExtendSectorExpiration.Repr"}.AssignLink(nil)
}
func (na *_MessageParamsMinerExtendSectorExpiration__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MessageParamsMinerExtendSectorExpiration); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "types.MessageParamsMinerExtendSectorExpiration.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MessageParamsMinerExtendSectorExpiration__ReprAssembler) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerExtendSectorExpiration__ReprPrototype{}
}
func (la *_MessageParamsMinerExtendSectorExpiration__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_MessageParamsMinerExtendSectorExpiration__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 1 {
		return nil // schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(1)} // FIXME: need an error thunking assembler!  it has returned.  sigh.
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_Extension.w = &la.w.Extension
		la.ca_Extension.m = &la.cm
		return &la.ca_Extension
	default:
		panic("unreachable")
	}
}
func (la *_MessageParamsMinerExtendSectorExpiration__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_MessageParamsMinerExtendSectorExpiration__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
