package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _MessageParamsMinerCheckSectorProven struct {
	SectorNumber _SectorNumber
}
type MessageParamsMinerCheckSectorProven = *_MessageParamsMinerCheckSectorProven

func (n _MessageParamsMinerCheckSectorProven) FieldSectorNumber()	SectorNumber {
	return &n.SectorNumber
}
type _MessageParamsMinerCheckSectorProven__Maybe struct {
	m schema.Maybe
	v MessageParamsMinerCheckSectorProven
}
type MaybeMessageParamsMinerCheckSectorProven = *_MessageParamsMinerCheckSectorProven__Maybe

func (m MaybeMessageParamsMinerCheckSectorProven) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeMessageParamsMinerCheckSectorProven) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeMessageParamsMinerCheckSectorProven) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeMessageParamsMinerCheckSectorProven) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeMessageParamsMinerCheckSectorProven) Must() MessageParamsMinerCheckSectorProven {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var (
	fieldName__MessageParamsMinerCheckSectorProven_SectorNumber = _String{"SectorNumber"}
)
var _ ipld.Node = (MessageParamsMinerCheckSectorProven)(&_MessageParamsMinerCheckSectorProven{})
var _ schema.TypedNode = (MessageParamsMinerCheckSectorProven)(&_MessageParamsMinerCheckSectorProven{})
func (MessageParamsMinerCheckSectorProven) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n MessageParamsMinerCheckSectorProven) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "SectorNumber":
		return &n.SectorNumber, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n MessageParamsMinerCheckSectorProven) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (MessageParamsMinerCheckSectorProven) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.MessageParamsMinerCheckSectorProven"}.LookupByIndex(0)
}
func (n MessageParamsMinerCheckSectorProven) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n MessageParamsMinerCheckSectorProven) MapIterator() ipld.MapIterator {
	return &_MessageParamsMinerCheckSectorProven__MapItr{n, 0}
}

type _MessageParamsMinerCheckSectorProven__MapItr struct {
	n MessageParamsMinerCheckSectorProven
	idx  int
}

func (itr *_MessageParamsMinerCheckSectorProven__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 1 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__MessageParamsMinerCheckSectorProven_SectorNumber
		v = &itr.n.SectorNumber
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MessageParamsMinerCheckSectorProven__MapItr) Done() bool {
	return itr.idx >= 1
}

func (MessageParamsMinerCheckSectorProven) ListIterator() ipld.ListIterator {
	return nil
}
func (MessageParamsMinerCheckSectorProven) Length() int {
	return 1
}
func (MessageParamsMinerCheckSectorProven) IsAbsent() bool {
	return false
}
func (MessageParamsMinerCheckSectorProven) IsNull() bool {
	return false
}
func (MessageParamsMinerCheckSectorProven) AsBool() (bool, error) {
	return mixins.Map{"types.MessageParamsMinerCheckSectorProven"}.AsBool()
}
func (MessageParamsMinerCheckSectorProven) AsInt() (int, error) {
	return mixins.Map{"types.MessageParamsMinerCheckSectorProven"}.AsInt()
}
func (MessageParamsMinerCheckSectorProven) AsFloat() (float64, error) {
	return mixins.Map{"types.MessageParamsMinerCheckSectorProven"}.AsFloat()
}
func (MessageParamsMinerCheckSectorProven) AsString() (string, error) {
	return mixins.Map{"types.MessageParamsMinerCheckSectorProven"}.AsString()
}
func (MessageParamsMinerCheckSectorProven) AsBytes() ([]byte, error) {
	return mixins.Map{"types.MessageParamsMinerCheckSectorProven"}.AsBytes()
}
func (MessageParamsMinerCheckSectorProven) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.MessageParamsMinerCheckSectorProven"}.AsLink()
}
func (MessageParamsMinerCheckSectorProven) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerCheckSectorProven__Prototype{}
}
type _MessageParamsMinerCheckSectorProven__Prototype struct{}

func (_MessageParamsMinerCheckSectorProven__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _MessageParamsMinerCheckSectorProven__Builder
	nb.Reset()
	return &nb
}
type _MessageParamsMinerCheckSectorProven__Builder struct {
	_MessageParamsMinerCheckSectorProven__Assembler
}
func (nb *_MessageParamsMinerCheckSectorProven__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MessageParamsMinerCheckSectorProven__Builder) Reset() {
	var w _MessageParamsMinerCheckSectorProven
	var m schema.Maybe
	*nb = _MessageParamsMinerCheckSectorProven__Builder{_MessageParamsMinerCheckSectorProven__Assembler{w: &w, m: &m}}
}
type _MessageParamsMinerCheckSectorProven__Assembler struct {
	w *_MessageParamsMinerCheckSectorProven
	m *schema.Maybe
	state maState
	s int
	f int

	cm schema.Maybe
	ca_SectorNumber _SectorNumber__Assembler
	}

func (na *_MessageParamsMinerCheckSectorProven__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_SectorNumber.reset()
}

var (
	fieldBit__MessageParamsMinerCheckSectorProven_SectorNumber = 1 << 0
	fieldBits__MessageParamsMinerCheckSectorProven_sufficient = 0 + 1 << 0
)
func (na *_MessageParamsMinerCheckSectorProven__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MessageParamsMinerCheckSectorProven{}
	}
	return na, nil
}
func (_MessageParamsMinerCheckSectorProven__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.MessageParamsMinerCheckSectorProven"}.BeginList(0)
}
func (na *_MessageParamsMinerCheckSectorProven__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.MessageParamsMinerCheckSectorProven"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MessageParamsMinerCheckSectorProven__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.MessageParamsMinerCheckSectorProven"}.AssignBool(false)
}
func (_MessageParamsMinerCheckSectorProven__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.MessageParamsMinerCheckSectorProven"}.AssignInt(0)
}
func (_MessageParamsMinerCheckSectorProven__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.MessageParamsMinerCheckSectorProven"}.AssignFloat(0)
}
func (_MessageParamsMinerCheckSectorProven__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.MessageParamsMinerCheckSectorProven"}.AssignString("")
}
func (_MessageParamsMinerCheckSectorProven__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.MessageParamsMinerCheckSectorProven"}.AssignBytes(nil)
}
func (_MessageParamsMinerCheckSectorProven__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.MessageParamsMinerCheckSectorProven"}.AssignLink(nil)
}
func (na *_MessageParamsMinerCheckSectorProven__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MessageParamsMinerCheckSectorProven); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.MessageParamsMinerCheckSectorProven", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MessageParamsMinerCheckSectorProven__Assembler) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerCheckSectorProven__Prototype{}
}
func (ma *_MessageParamsMinerCheckSectorProven__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_SectorNumber.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_MessageParamsMinerCheckSectorProven__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "SectorNumber":
		if ma.s & fieldBit__MessageParamsMinerCheckSectorProven_SectorNumber != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MessageParamsMinerCheckSectorProven_SectorNumber}
		}
		ma.s += fieldBit__MessageParamsMinerCheckSectorProven_SectorNumber
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_SectorNumber.w = &ma.w.SectorNumber
		ma.ca_SectorNumber.m = &ma.cm
		return &ma.ca_SectorNumber, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName:"types.MessageParamsMinerCheckSectorProven", Key:&_String{k}}
	}
}
func (ma *_MessageParamsMinerCheckSectorProven__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_MessageParamsMinerCheckSectorProven__KeyAssembler)(ma)
}
func (ma *_MessageParamsMinerCheckSectorProven__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_SectorNumber.w = &ma.w.SectorNumber
		ma.ca_SectorNumber.m = &ma.cm
		return &ma.ca_SectorNumber
	default:
		panic("unreachable")
	}
}
func (ma *_MessageParamsMinerCheckSectorProven__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_MessageParamsMinerCheckSectorProven__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_MessageParamsMinerCheckSectorProven__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}
type _MessageParamsMinerCheckSectorProven__KeyAssembler _MessageParamsMinerCheckSectorProven__Assembler
func (_MessageParamsMinerCheckSectorProven__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"types.MessageParamsMinerCheckSectorProven.KeyAssembler"}.BeginMap(0)
}
func (_MessageParamsMinerCheckSectorProven__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"types.MessageParamsMinerCheckSectorProven.KeyAssembler"}.BeginList(0)
}
func (na *_MessageParamsMinerCheckSectorProven__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"types.MessageParamsMinerCheckSectorProven.KeyAssembler"}.AssignNull()
}
func (_MessageParamsMinerCheckSectorProven__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"types.MessageParamsMinerCheckSectorProven.KeyAssembler"}.AssignBool(false)
}
func (_MessageParamsMinerCheckSectorProven__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"types.MessageParamsMinerCheckSectorProven.KeyAssembler"}.AssignInt(0)
}
func (_MessageParamsMinerCheckSectorProven__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"types.MessageParamsMinerCheckSectorProven.KeyAssembler"}.AssignFloat(0)
}
func (ka *_MessageParamsMinerCheckSectorProven__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "SectorNumber":
		if ka.s & fieldBit__MessageParamsMinerCheckSectorProven_SectorNumber != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MessageParamsMinerCheckSectorProven_SectorNumber}
		}
		ka.s += fieldBit__MessageParamsMinerCheckSectorProven_SectorNumber
		ka.state = maState_expectValue
		ka.f = 0
	default:
		return ipld.ErrInvalidKey{TypeName:"types.MessageParamsMinerCheckSectorProven", Key:&_String{k}}
	}
	return nil
}
func (_MessageParamsMinerCheckSectorProven__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"types.MessageParamsMinerCheckSectorProven.KeyAssembler"}.AssignBytes(nil)
}
func (_MessageParamsMinerCheckSectorProven__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"types.MessageParamsMinerCheckSectorProven.KeyAssembler"}.AssignLink(nil)
}
func (ka *_MessageParamsMinerCheckSectorProven__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_MessageParamsMinerCheckSectorProven__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (MessageParamsMinerCheckSectorProven) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n MessageParamsMinerCheckSectorProven) Representation() ipld.Node {
	return (*_MessageParamsMinerCheckSectorProven__Repr)(n)
}
type _MessageParamsMinerCheckSectorProven__Repr _MessageParamsMinerCheckSectorProven
var _ ipld.Node = &_MessageParamsMinerCheckSectorProven__Repr{}
func (_MessageParamsMinerCheckSectorProven__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_MessageParamsMinerCheckSectorProven__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"types.MessageParamsMinerCheckSectorProven.Repr"}.LookupByString("")
}
func (n *_MessageParamsMinerCheckSectorProven__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_MessageParamsMinerCheckSectorProven__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.SectorNumber.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _MessageParamsMinerCheckSectorProven__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "types.MessageParamsMinerCheckSectorProven.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_MessageParamsMinerCheckSectorProven__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_MessageParamsMinerCheckSectorProven__Repr) ListIterator() ipld.ListIterator {
	return &_MessageParamsMinerCheckSectorProven__ReprListItr{n, 0}
}

type _MessageParamsMinerCheckSectorProven__ReprListItr struct {
	n   *_MessageParamsMinerCheckSectorProven__Repr
	idx int
	
}

func (itr *_MessageParamsMinerCheckSectorProven__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 1 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.SectorNumber.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MessageParamsMinerCheckSectorProven__ReprListItr) Done() bool {
	return itr.idx >= 1
}

func (rn *_MessageParamsMinerCheckSectorProven__Repr) Length() int {
	l := 1
	return l
}
func (_MessageParamsMinerCheckSectorProven__Repr) IsAbsent() bool {
	return false
}
func (_MessageParamsMinerCheckSectorProven__Repr) IsNull() bool {
	return false
}
func (_MessageParamsMinerCheckSectorProven__Repr) AsBool() (bool, error) {
	return mixins.List{"types.MessageParamsMinerCheckSectorProven.Repr"}.AsBool()
}
func (_MessageParamsMinerCheckSectorProven__Repr) AsInt() (int, error) {
	return mixins.List{"types.MessageParamsMinerCheckSectorProven.Repr"}.AsInt()
}
func (_MessageParamsMinerCheckSectorProven__Repr) AsFloat() (float64, error) {
	return mixins.List{"types.MessageParamsMinerCheckSectorProven.Repr"}.AsFloat()
}
func (_MessageParamsMinerCheckSectorProven__Repr) AsString() (string, error) {
	return mixins.List{"types.MessageParamsMinerCheckSectorProven.Repr"}.AsString()
}
func (_MessageParamsMinerCheckSectorProven__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"types.MessageParamsMinerCheckSectorProven.Repr"}.AsBytes()
}
func (_MessageParamsMinerCheckSectorProven__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"types.MessageParamsMinerCheckSectorProven.Repr"}.AsLink()
}
func (_MessageParamsMinerCheckSectorProven__Repr) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerCheckSectorProven__ReprPrototype{}
}
type _MessageParamsMinerCheckSectorProven__ReprPrototype struct{}

func (_MessageParamsMinerCheckSectorProven__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _MessageParamsMinerCheckSectorProven__ReprBuilder
	nb.Reset()
	return &nb
}
type _MessageParamsMinerCheckSectorProven__ReprBuilder struct {
	_MessageParamsMinerCheckSectorProven__ReprAssembler
}
func (nb *_MessageParamsMinerCheckSectorProven__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MessageParamsMinerCheckSectorProven__ReprBuilder) Reset() {
	var w _MessageParamsMinerCheckSectorProven
	var m schema.Maybe
	*nb = _MessageParamsMinerCheckSectorProven__ReprBuilder{_MessageParamsMinerCheckSectorProven__ReprAssembler{w: &w, m: &m}}
}
type _MessageParamsMinerCheckSectorProven__ReprAssembler struct {
	w *_MessageParamsMinerCheckSectorProven
	m *schema.Maybe
	state laState
	f int

	cm schema.Maybe
	ca_SectorNumber _SectorNumber__ReprAssembler
	}

func (na *_MessageParamsMinerCheckSectorProven__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_SectorNumber.reset()
}
func (_MessageParamsMinerCheckSectorProven__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"types.MessageParamsMinerCheckSectorProven.Repr"}.BeginMap(0)
}
func (na *_MessageParamsMinerCheckSectorProven__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MessageParamsMinerCheckSectorProven{}
	}
	return na, nil
}
func (na *_MessageParamsMinerCheckSectorProven__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"types.MessageParamsMinerCheckSectorProven.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MessageParamsMinerCheckSectorProven__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"types.MessageParamsMinerCheckSectorProven.Repr"}.AssignBool(false)
}
func (_MessageParamsMinerCheckSectorProven__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"types.MessageParamsMinerCheckSectorProven.Repr"}.AssignInt(0)
}
func (_MessageParamsMinerCheckSectorProven__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"types.MessageParamsMinerCheckSectorProven.Repr"}.AssignFloat(0)
}
func (_MessageParamsMinerCheckSectorProven__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"types.MessageParamsMinerCheckSectorProven.Repr"}.AssignString("")
}
func (_MessageParamsMinerCheckSectorProven__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"types.MessageParamsMinerCheckSectorProven.Repr"}.AssignBytes(nil)
}
func (_MessageParamsMinerCheckSectorProven__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"types.MessageParamsMinerCheckSectorProven.Repr"}.AssignLink(nil)
}
func (na *_MessageParamsMinerCheckSectorProven__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MessageParamsMinerCheckSectorProven); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "types.MessageParamsMinerCheckSectorProven.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MessageParamsMinerCheckSectorProven__ReprAssembler) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerCheckSectorProven__ReprPrototype{}
}
func (la *_MessageParamsMinerCheckSectorProven__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_MessageParamsMinerCheckSectorProven__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 1 {
		return _ErrorThunkAssembler{schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(1)}}
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_SectorNumber.w = &la.w.SectorNumber
		la.ca_SectorNumber.m = &la.cm
		return &la.ca_SectorNumber
	default:
		panic("unreachable")
	}
}
func (la *_MessageParamsMinerCheckSectorProven__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_MessageParamsMinerCheckSectorProven__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
