package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _MessageParamsPaychConstructor struct {
	From _Address
	To _Address
}
type MessageParamsPaychConstructor = *_MessageParamsPaychConstructor

func (n _MessageParamsPaychConstructor) FieldFrom()	Address {
	return &n.From
}
func (n _MessageParamsPaychConstructor) FieldTo()	Address {
	return &n.To
}
type _MessageParamsPaychConstructor__Maybe struct {
	m schema.Maybe
	v MessageParamsPaychConstructor
}
type MaybeMessageParamsPaychConstructor = *_MessageParamsPaychConstructor__Maybe

func (m MaybeMessageParamsPaychConstructor) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeMessageParamsPaychConstructor) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeMessageParamsPaychConstructor) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeMessageParamsPaychConstructor) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeMessageParamsPaychConstructor) Must() MessageParamsPaychConstructor {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var (
	fieldName__MessageParamsPaychConstructor_From = _String{"From"}
	fieldName__MessageParamsPaychConstructor_To = _String{"To"}
)
var _ ipld.Node = (MessageParamsPaychConstructor)(&_MessageParamsPaychConstructor{})
var _ schema.TypedNode = (MessageParamsPaychConstructor)(&_MessageParamsPaychConstructor{})
func (MessageParamsPaychConstructor) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n MessageParamsPaychConstructor) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "From":
		return &n.From, nil
	case "To":
		return &n.To, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n MessageParamsPaychConstructor) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (MessageParamsPaychConstructor) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.MessageParamsPaychConstructor"}.LookupByIndex(0)
}
func (n MessageParamsPaychConstructor) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n MessageParamsPaychConstructor) MapIterator() ipld.MapIterator {
	return &_MessageParamsPaychConstructor__MapItr{n, 0}
}

type _MessageParamsPaychConstructor__MapItr struct {
	n MessageParamsPaychConstructor
	idx  int
}

func (itr *_MessageParamsPaychConstructor__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 2 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__MessageParamsPaychConstructor_From
		v = &itr.n.From
	case 1:
		k = &fieldName__MessageParamsPaychConstructor_To
		v = &itr.n.To
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MessageParamsPaychConstructor__MapItr) Done() bool {
	return itr.idx >= 2
}

func (MessageParamsPaychConstructor) ListIterator() ipld.ListIterator {
	return nil
}
func (MessageParamsPaychConstructor) Length() int {
	return 2
}
func (MessageParamsPaychConstructor) IsAbsent() bool {
	return false
}
func (MessageParamsPaychConstructor) IsNull() bool {
	return false
}
func (MessageParamsPaychConstructor) AsBool() (bool, error) {
	return mixins.Map{"types.MessageParamsPaychConstructor"}.AsBool()
}
func (MessageParamsPaychConstructor) AsInt() (int, error) {
	return mixins.Map{"types.MessageParamsPaychConstructor"}.AsInt()
}
func (MessageParamsPaychConstructor) AsFloat() (float64, error) {
	return mixins.Map{"types.MessageParamsPaychConstructor"}.AsFloat()
}
func (MessageParamsPaychConstructor) AsString() (string, error) {
	return mixins.Map{"types.MessageParamsPaychConstructor"}.AsString()
}
func (MessageParamsPaychConstructor) AsBytes() ([]byte, error) {
	return mixins.Map{"types.MessageParamsPaychConstructor"}.AsBytes()
}
func (MessageParamsPaychConstructor) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.MessageParamsPaychConstructor"}.AsLink()
}
func (MessageParamsPaychConstructor) Prototype() ipld.NodePrototype {
	return _MessageParamsPaychConstructor__Prototype{}
}
type _MessageParamsPaychConstructor__Prototype struct{}

func (_MessageParamsPaychConstructor__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _MessageParamsPaychConstructor__Builder
	nb.Reset()
	return &nb
}
type _MessageParamsPaychConstructor__Builder struct {
	_MessageParamsPaychConstructor__Assembler
}
func (nb *_MessageParamsPaychConstructor__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MessageParamsPaychConstructor__Builder) Reset() {
	var w _MessageParamsPaychConstructor
	var m schema.Maybe
	*nb = _MessageParamsPaychConstructor__Builder{_MessageParamsPaychConstructor__Assembler{w: &w, m: &m}}
}
type _MessageParamsPaychConstructor__Assembler struct {
	w *_MessageParamsPaychConstructor
	m *schema.Maybe
	state maState
	s int
	f int

	cm schema.Maybe
	ca_From _Address__Assembler
	ca_To _Address__Assembler
	}

func (na *_MessageParamsPaychConstructor__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_From.reset()
	na.ca_To.reset()
}

var (
	fieldBit__MessageParamsPaychConstructor_From = 1 << 0
	fieldBit__MessageParamsPaychConstructor_To = 1 << 1
	fieldBits__MessageParamsPaychConstructor_sufficient = 0 + 1 << 0 + 1 << 1
)
func (na *_MessageParamsPaychConstructor__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MessageParamsPaychConstructor{}
	}
	return na, nil
}
func (_MessageParamsPaychConstructor__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.MessageParamsPaychConstructor"}.BeginList(0)
}
func (na *_MessageParamsPaychConstructor__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.MessageParamsPaychConstructor"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MessageParamsPaychConstructor__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.MessageParamsPaychConstructor"}.AssignBool(false)
}
func (_MessageParamsPaychConstructor__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.MessageParamsPaychConstructor"}.AssignInt(0)
}
func (_MessageParamsPaychConstructor__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.MessageParamsPaychConstructor"}.AssignFloat(0)
}
func (_MessageParamsPaychConstructor__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.MessageParamsPaychConstructor"}.AssignString("")
}
func (_MessageParamsPaychConstructor__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.MessageParamsPaychConstructor"}.AssignBytes(nil)
}
func (_MessageParamsPaychConstructor__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.MessageParamsPaychConstructor"}.AssignLink(nil)
}
func (na *_MessageParamsPaychConstructor__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MessageParamsPaychConstructor); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.MessageParamsPaychConstructor", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MessageParamsPaychConstructor__Assembler) Prototype() ipld.NodePrototype {
	return _MessageParamsPaychConstructor__Prototype{}
}
func (ma *_MessageParamsPaychConstructor__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_From.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 1:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_To.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_MessageParamsPaychConstructor__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "From":
		if ma.s & fieldBit__MessageParamsPaychConstructor_From != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MessageParamsPaychConstructor_From}
		}
		ma.s += fieldBit__MessageParamsPaychConstructor_From
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_From.w = &ma.w.From
		ma.ca_From.m = &ma.cm
		return &ma.ca_From, nil
	case "To":
		if ma.s & fieldBit__MessageParamsPaychConstructor_To != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MessageParamsPaychConstructor_To}
		}
		ma.s += fieldBit__MessageParamsPaychConstructor_To
		ma.state = maState_midValue
		ma.f = 1
		ma.ca_To.w = &ma.w.To
		ma.ca_To.m = &ma.cm
		return &ma.ca_To, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName:"types.MessageParamsPaychConstructor", Key:&_String{k}}
	}
}
func (ma *_MessageParamsPaychConstructor__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_MessageParamsPaychConstructor__KeyAssembler)(ma)
}
func (ma *_MessageParamsPaychConstructor__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_From.w = &ma.w.From
		ma.ca_From.m = &ma.cm
		return &ma.ca_From
	case 1:
		ma.ca_To.w = &ma.w.To
		ma.ca_To.m = &ma.cm
		return &ma.ca_To
	default:
		panic("unreachable")
	}
}
func (ma *_MessageParamsPaychConstructor__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_MessageParamsPaychConstructor__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_MessageParamsPaychConstructor__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}
type _MessageParamsPaychConstructor__KeyAssembler _MessageParamsPaychConstructor__Assembler
func (_MessageParamsPaychConstructor__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"types.MessageParamsPaychConstructor.KeyAssembler"}.BeginMap(0)
}
func (_MessageParamsPaychConstructor__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"types.MessageParamsPaychConstructor.KeyAssembler"}.BeginList(0)
}
func (na *_MessageParamsPaychConstructor__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"types.MessageParamsPaychConstructor.KeyAssembler"}.AssignNull()
}
func (_MessageParamsPaychConstructor__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"types.MessageParamsPaychConstructor.KeyAssembler"}.AssignBool(false)
}
func (_MessageParamsPaychConstructor__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"types.MessageParamsPaychConstructor.KeyAssembler"}.AssignInt(0)
}
func (_MessageParamsPaychConstructor__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"types.MessageParamsPaychConstructor.KeyAssembler"}.AssignFloat(0)
}
func (ka *_MessageParamsPaychConstructor__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "From":
		if ka.s & fieldBit__MessageParamsPaychConstructor_From != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MessageParamsPaychConstructor_From}
		}
		ka.s += fieldBit__MessageParamsPaychConstructor_From
		ka.state = maState_expectValue
		ka.f = 0
	case "To":
		if ka.s & fieldBit__MessageParamsPaychConstructor_To != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MessageParamsPaychConstructor_To}
		}
		ka.s += fieldBit__MessageParamsPaychConstructor_To
		ka.state = maState_expectValue
		ka.f = 1
	default:
		return ipld.ErrInvalidKey{TypeName:"types.MessageParamsPaychConstructor", Key:&_String{k}}
	}
	return nil
}
func (_MessageParamsPaychConstructor__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"types.MessageParamsPaychConstructor.KeyAssembler"}.AssignBytes(nil)
}
func (_MessageParamsPaychConstructor__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"types.MessageParamsPaychConstructor.KeyAssembler"}.AssignLink(nil)
}
func (ka *_MessageParamsPaychConstructor__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_MessageParamsPaychConstructor__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (MessageParamsPaychConstructor) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n MessageParamsPaychConstructor) Representation() ipld.Node {
	return (*_MessageParamsPaychConstructor__Repr)(n)
}
type _MessageParamsPaychConstructor__Repr _MessageParamsPaychConstructor
var _ ipld.Node = &_MessageParamsPaychConstructor__Repr{}
func (_MessageParamsPaychConstructor__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_MessageParamsPaychConstructor__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"types.MessageParamsPaychConstructor.Repr"}.LookupByString("")
}
func (n *_MessageParamsPaychConstructor__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_MessageParamsPaychConstructor__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.From.Representation(), nil
	case 1:
		return n.To.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _MessageParamsPaychConstructor__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "types.MessageParamsPaychConstructor.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_MessageParamsPaychConstructor__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_MessageParamsPaychConstructor__Repr) ListIterator() ipld.ListIterator {
	return &_MessageParamsPaychConstructor__ReprListItr{n, 0}
}

type _MessageParamsPaychConstructor__ReprListItr struct {
	n   *_MessageParamsPaychConstructor__Repr
	idx int
	
}

func (itr *_MessageParamsPaychConstructor__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 2 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.From.Representation()
	case 1:
		idx = itr.idx
		v = itr.n.To.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MessageParamsPaychConstructor__ReprListItr) Done() bool {
	return itr.idx >= 2
}

func (rn *_MessageParamsPaychConstructor__Repr) Length() int {
	l := 2
	return l
}
func (_MessageParamsPaychConstructor__Repr) IsAbsent() bool {
	return false
}
func (_MessageParamsPaychConstructor__Repr) IsNull() bool {
	return false
}
func (_MessageParamsPaychConstructor__Repr) AsBool() (bool, error) {
	return mixins.List{"types.MessageParamsPaychConstructor.Repr"}.AsBool()
}
func (_MessageParamsPaychConstructor__Repr) AsInt() (int, error) {
	return mixins.List{"types.MessageParamsPaychConstructor.Repr"}.AsInt()
}
func (_MessageParamsPaychConstructor__Repr) AsFloat() (float64, error) {
	return mixins.List{"types.MessageParamsPaychConstructor.Repr"}.AsFloat()
}
func (_MessageParamsPaychConstructor__Repr) AsString() (string, error) {
	return mixins.List{"types.MessageParamsPaychConstructor.Repr"}.AsString()
}
func (_MessageParamsPaychConstructor__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"types.MessageParamsPaychConstructor.Repr"}.AsBytes()
}
func (_MessageParamsPaychConstructor__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"types.MessageParamsPaychConstructor.Repr"}.AsLink()
}
func (_MessageParamsPaychConstructor__Repr) Prototype() ipld.NodePrototype {
	return _MessageParamsPaychConstructor__ReprPrototype{}
}
type _MessageParamsPaychConstructor__ReprPrototype struct{}

func (_MessageParamsPaychConstructor__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _MessageParamsPaychConstructor__ReprBuilder
	nb.Reset()
	return &nb
}
type _MessageParamsPaychConstructor__ReprBuilder struct {
	_MessageParamsPaychConstructor__ReprAssembler
}
func (nb *_MessageParamsPaychConstructor__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MessageParamsPaychConstructor__ReprBuilder) Reset() {
	var w _MessageParamsPaychConstructor
	var m schema.Maybe
	*nb = _MessageParamsPaychConstructor__ReprBuilder{_MessageParamsPaychConstructor__ReprAssembler{w: &w, m: &m}}
}
type _MessageParamsPaychConstructor__ReprAssembler struct {
	w *_MessageParamsPaychConstructor
	m *schema.Maybe
	state laState
	f int

	cm schema.Maybe
	ca_From _Address__ReprAssembler
	ca_To _Address__ReprAssembler
	}

func (na *_MessageParamsPaychConstructor__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_From.reset()
	na.ca_To.reset()
}
func (_MessageParamsPaychConstructor__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"types.MessageParamsPaychConstructor.Repr"}.BeginMap(0)
}
func (na *_MessageParamsPaychConstructor__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MessageParamsPaychConstructor{}
	}
	return na, nil
}
func (na *_MessageParamsPaychConstructor__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"types.MessageParamsPaychConstructor.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MessageParamsPaychConstructor__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"types.MessageParamsPaychConstructor.Repr"}.AssignBool(false)
}
func (_MessageParamsPaychConstructor__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"types.MessageParamsPaychConstructor.Repr"}.AssignInt(0)
}
func (_MessageParamsPaychConstructor__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"types.MessageParamsPaychConstructor.Repr"}.AssignFloat(0)
}
func (_MessageParamsPaychConstructor__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"types.MessageParamsPaychConstructor.Repr"}.AssignString("")
}
func (_MessageParamsPaychConstructor__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"types.MessageParamsPaychConstructor.Repr"}.AssignBytes(nil)
}
func (_MessageParamsPaychConstructor__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"types.MessageParamsPaychConstructor.Repr"}.AssignLink(nil)
}
func (na *_MessageParamsPaychConstructor__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MessageParamsPaychConstructor); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "types.MessageParamsPaychConstructor.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MessageParamsPaychConstructor__ReprAssembler) Prototype() ipld.NodePrototype {
	return _MessageParamsPaychConstructor__ReprPrototype{}
}
func (la *_MessageParamsPaychConstructor__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 1:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_MessageParamsPaychConstructor__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 2 {
		return nil // schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(2)} // FIXME: need an error thunking assembler!  it has returned.  sigh.
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_From.w = &la.w.From
		la.ca_From.m = &la.cm
		return &la.ca_From
	case 1:
		la.ca_To.w = &la.w.To
		la.ca_To.m = &la.cm
		return &la.ca_To
	default:
		panic("unreachable")
	}
}
func (la *_MessageParamsPaychConstructor__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_MessageParamsPaychConstructor__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
