package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _MessageParamsVerifregAddVerifier struct {
	Address _Address
	Allowance _BigInt
}
type MessageParamsVerifregAddVerifier = *_MessageParamsVerifregAddVerifier

func (n _MessageParamsVerifregAddVerifier) FieldAddress()	Address {
	return &n.Address
}
func (n _MessageParamsVerifregAddVerifier) FieldAllowance()	BigInt {
	return &n.Allowance
}
type _MessageParamsVerifregAddVerifier__Maybe struct {
	m schema.Maybe
	v MessageParamsVerifregAddVerifier
}
type MaybeMessageParamsVerifregAddVerifier = *_MessageParamsVerifregAddVerifier__Maybe

func (m MaybeMessageParamsVerifregAddVerifier) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeMessageParamsVerifregAddVerifier) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeMessageParamsVerifregAddVerifier) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeMessageParamsVerifregAddVerifier) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeMessageParamsVerifregAddVerifier) Must() MessageParamsVerifregAddVerifier {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var (
	fieldName__MessageParamsVerifregAddVerifier_Address = _String{"Address"}
	fieldName__MessageParamsVerifregAddVerifier_Allowance = _String{"Allowance"}
)
var _ ipld.Node = (MessageParamsVerifregAddVerifier)(&_MessageParamsVerifregAddVerifier{})
var _ schema.TypedNode = (MessageParamsVerifregAddVerifier)(&_MessageParamsVerifregAddVerifier{})
func (MessageParamsVerifregAddVerifier) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n MessageParamsVerifregAddVerifier) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "Address":
		return &n.Address, nil
	case "Allowance":
		return &n.Allowance, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n MessageParamsVerifregAddVerifier) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (MessageParamsVerifregAddVerifier) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.MessageParamsVerifregAddVerifier"}.LookupByIndex(0)
}
func (n MessageParamsVerifregAddVerifier) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n MessageParamsVerifregAddVerifier) MapIterator() ipld.MapIterator {
	return &_MessageParamsVerifregAddVerifier__MapItr{n, 0}
}

type _MessageParamsVerifregAddVerifier__MapItr struct {
	n MessageParamsVerifregAddVerifier
	idx  int
}

func (itr *_MessageParamsVerifregAddVerifier__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 2 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__MessageParamsVerifregAddVerifier_Address
		v = &itr.n.Address
	case 1:
		k = &fieldName__MessageParamsVerifregAddVerifier_Allowance
		v = &itr.n.Allowance
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MessageParamsVerifregAddVerifier__MapItr) Done() bool {
	return itr.idx >= 2
}

func (MessageParamsVerifregAddVerifier) ListIterator() ipld.ListIterator {
	return nil
}
func (MessageParamsVerifregAddVerifier) Length() int {
	return 2
}
func (MessageParamsVerifregAddVerifier) IsAbsent() bool {
	return false
}
func (MessageParamsVerifregAddVerifier) IsNull() bool {
	return false
}
func (MessageParamsVerifregAddVerifier) AsBool() (bool, error) {
	return mixins.Map{"types.MessageParamsVerifregAddVerifier"}.AsBool()
}
func (MessageParamsVerifregAddVerifier) AsInt() (int, error) {
	return mixins.Map{"types.MessageParamsVerifregAddVerifier"}.AsInt()
}
func (MessageParamsVerifregAddVerifier) AsFloat() (float64, error) {
	return mixins.Map{"types.MessageParamsVerifregAddVerifier"}.AsFloat()
}
func (MessageParamsVerifregAddVerifier) AsString() (string, error) {
	return mixins.Map{"types.MessageParamsVerifregAddVerifier"}.AsString()
}
func (MessageParamsVerifregAddVerifier) AsBytes() ([]byte, error) {
	return mixins.Map{"types.MessageParamsVerifregAddVerifier"}.AsBytes()
}
func (MessageParamsVerifregAddVerifier) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.MessageParamsVerifregAddVerifier"}.AsLink()
}
func (MessageParamsVerifregAddVerifier) Prototype() ipld.NodePrototype {
	return _MessageParamsVerifregAddVerifier__Prototype{}
}
type _MessageParamsVerifregAddVerifier__Prototype struct{}

func (_MessageParamsVerifregAddVerifier__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _MessageParamsVerifregAddVerifier__Builder
	nb.Reset()
	return &nb
}
type _MessageParamsVerifregAddVerifier__Builder struct {
	_MessageParamsVerifregAddVerifier__Assembler
}
func (nb *_MessageParamsVerifregAddVerifier__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MessageParamsVerifregAddVerifier__Builder) Reset() {
	var w _MessageParamsVerifregAddVerifier
	var m schema.Maybe
	*nb = _MessageParamsVerifregAddVerifier__Builder{_MessageParamsVerifregAddVerifier__Assembler{w: &w, m: &m}}
}
type _MessageParamsVerifregAddVerifier__Assembler struct {
	w *_MessageParamsVerifregAddVerifier
	m *schema.Maybe
	state maState
	s int
	f int

	cm schema.Maybe
	ca_Address _Address__Assembler
	ca_Allowance _BigInt__Assembler
	}

func (na *_MessageParamsVerifregAddVerifier__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_Address.reset()
	na.ca_Allowance.reset()
}

var (
	fieldBit__MessageParamsVerifregAddVerifier_Address = 1 << 0
	fieldBit__MessageParamsVerifregAddVerifier_Allowance = 1 << 1
	fieldBits__MessageParamsVerifregAddVerifier_sufficient = 0 + 1 << 0 + 1 << 1
)
func (na *_MessageParamsVerifregAddVerifier__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MessageParamsVerifregAddVerifier{}
	}
	return na, nil
}
func (_MessageParamsVerifregAddVerifier__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.MessageParamsVerifregAddVerifier"}.BeginList(0)
}
func (na *_MessageParamsVerifregAddVerifier__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.MessageParamsVerifregAddVerifier"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MessageParamsVerifregAddVerifier__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.MessageParamsVerifregAddVerifier"}.AssignBool(false)
}
func (_MessageParamsVerifregAddVerifier__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.MessageParamsVerifregAddVerifier"}.AssignInt(0)
}
func (_MessageParamsVerifregAddVerifier__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.MessageParamsVerifregAddVerifier"}.AssignFloat(0)
}
func (_MessageParamsVerifregAddVerifier__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.MessageParamsVerifregAddVerifier"}.AssignString("")
}
func (_MessageParamsVerifregAddVerifier__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.MessageParamsVerifregAddVerifier"}.AssignBytes(nil)
}
func (_MessageParamsVerifregAddVerifier__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.MessageParamsVerifregAddVerifier"}.AssignLink(nil)
}
func (na *_MessageParamsVerifregAddVerifier__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MessageParamsVerifregAddVerifier); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.MessageParamsVerifregAddVerifier", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MessageParamsVerifregAddVerifier__Assembler) Prototype() ipld.NodePrototype {
	return _MessageParamsVerifregAddVerifier__Prototype{}
}
func (ma *_MessageParamsVerifregAddVerifier__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_Address.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 1:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_Allowance.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_MessageParamsVerifregAddVerifier__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "Address":
		if ma.s & fieldBit__MessageParamsVerifregAddVerifier_Address != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MessageParamsVerifregAddVerifier_Address}
		}
		ma.s += fieldBit__MessageParamsVerifregAddVerifier_Address
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_Address.w = &ma.w.Address
		ma.ca_Address.m = &ma.cm
		return &ma.ca_Address, nil
	case "Allowance":
		if ma.s & fieldBit__MessageParamsVerifregAddVerifier_Allowance != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MessageParamsVerifregAddVerifier_Allowance}
		}
		ma.s += fieldBit__MessageParamsVerifregAddVerifier_Allowance
		ma.state = maState_midValue
		ma.f = 1
		ma.ca_Allowance.w = &ma.w.Allowance
		ma.ca_Allowance.m = &ma.cm
		return &ma.ca_Allowance, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName:"types.MessageParamsVerifregAddVerifier", Key:&_String{k}}
	}
}
func (ma *_MessageParamsVerifregAddVerifier__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_MessageParamsVerifregAddVerifier__KeyAssembler)(ma)
}
func (ma *_MessageParamsVerifregAddVerifier__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_Address.w = &ma.w.Address
		ma.ca_Address.m = &ma.cm
		return &ma.ca_Address
	case 1:
		ma.ca_Allowance.w = &ma.w.Allowance
		ma.ca_Allowance.m = &ma.cm
		return &ma.ca_Allowance
	default:
		panic("unreachable")
	}
}
func (ma *_MessageParamsVerifregAddVerifier__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_MessageParamsVerifregAddVerifier__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_MessageParamsVerifregAddVerifier__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}
type _MessageParamsVerifregAddVerifier__KeyAssembler _MessageParamsVerifregAddVerifier__Assembler
func (_MessageParamsVerifregAddVerifier__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"types.MessageParamsVerifregAddVerifier.KeyAssembler"}.BeginMap(0)
}
func (_MessageParamsVerifregAddVerifier__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"types.MessageParamsVerifregAddVerifier.KeyAssembler"}.BeginList(0)
}
func (na *_MessageParamsVerifregAddVerifier__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"types.MessageParamsVerifregAddVerifier.KeyAssembler"}.AssignNull()
}
func (_MessageParamsVerifregAddVerifier__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"types.MessageParamsVerifregAddVerifier.KeyAssembler"}.AssignBool(false)
}
func (_MessageParamsVerifregAddVerifier__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"types.MessageParamsVerifregAddVerifier.KeyAssembler"}.AssignInt(0)
}
func (_MessageParamsVerifregAddVerifier__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"types.MessageParamsVerifregAddVerifier.KeyAssembler"}.AssignFloat(0)
}
func (ka *_MessageParamsVerifregAddVerifier__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "Address":
		if ka.s & fieldBit__MessageParamsVerifregAddVerifier_Address != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MessageParamsVerifregAddVerifier_Address}
		}
		ka.s += fieldBit__MessageParamsVerifregAddVerifier_Address
		ka.state = maState_expectValue
		ka.f = 0
	case "Allowance":
		if ka.s & fieldBit__MessageParamsVerifregAddVerifier_Allowance != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MessageParamsVerifregAddVerifier_Allowance}
		}
		ka.s += fieldBit__MessageParamsVerifregAddVerifier_Allowance
		ka.state = maState_expectValue
		ka.f = 1
	default:
		return ipld.ErrInvalidKey{TypeName:"types.MessageParamsVerifregAddVerifier", Key:&_String{k}}
	}
	return nil
}
func (_MessageParamsVerifregAddVerifier__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"types.MessageParamsVerifregAddVerifier.KeyAssembler"}.AssignBytes(nil)
}
func (_MessageParamsVerifregAddVerifier__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"types.MessageParamsVerifregAddVerifier.KeyAssembler"}.AssignLink(nil)
}
func (ka *_MessageParamsVerifregAddVerifier__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_MessageParamsVerifregAddVerifier__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (MessageParamsVerifregAddVerifier) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n MessageParamsVerifregAddVerifier) Representation() ipld.Node {
	return (*_MessageParamsVerifregAddVerifier__Repr)(n)
}
type _MessageParamsVerifregAddVerifier__Repr _MessageParamsVerifregAddVerifier
var _ ipld.Node = &_MessageParamsVerifregAddVerifier__Repr{}
func (_MessageParamsVerifregAddVerifier__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_MessageParamsVerifregAddVerifier__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"types.MessageParamsVerifregAddVerifier.Repr"}.LookupByString("")
}
func (n *_MessageParamsVerifregAddVerifier__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_MessageParamsVerifregAddVerifier__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.Address.Representation(), nil
	case 1:
		return n.Allowance.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _MessageParamsVerifregAddVerifier__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "types.MessageParamsVerifregAddVerifier.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_MessageParamsVerifregAddVerifier__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_MessageParamsVerifregAddVerifier__Repr) ListIterator() ipld.ListIterator {
	return &_MessageParamsVerifregAddVerifier__ReprListItr{n, 0}
}

type _MessageParamsVerifregAddVerifier__ReprListItr struct {
	n   *_MessageParamsVerifregAddVerifier__Repr
	idx int
	
}

func (itr *_MessageParamsVerifregAddVerifier__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 2 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.Address.Representation()
	case 1:
		idx = itr.idx
		v = itr.n.Allowance.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MessageParamsVerifregAddVerifier__ReprListItr) Done() bool {
	return itr.idx >= 2
}

func (rn *_MessageParamsVerifregAddVerifier__Repr) Length() int {
	l := 2
	return l
}
func (_MessageParamsVerifregAddVerifier__Repr) IsAbsent() bool {
	return false
}
func (_MessageParamsVerifregAddVerifier__Repr) IsNull() bool {
	return false
}
func (_MessageParamsVerifregAddVerifier__Repr) AsBool() (bool, error) {
	return mixins.List{"types.MessageParamsVerifregAddVerifier.Repr"}.AsBool()
}
func (_MessageParamsVerifregAddVerifier__Repr) AsInt() (int, error) {
	return mixins.List{"types.MessageParamsVerifregAddVerifier.Repr"}.AsInt()
}
func (_MessageParamsVerifregAddVerifier__Repr) AsFloat() (float64, error) {
	return mixins.List{"types.MessageParamsVerifregAddVerifier.Repr"}.AsFloat()
}
func (_MessageParamsVerifregAddVerifier__Repr) AsString() (string, error) {
	return mixins.List{"types.MessageParamsVerifregAddVerifier.Repr"}.AsString()
}
func (_MessageParamsVerifregAddVerifier__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"types.MessageParamsVerifregAddVerifier.Repr"}.AsBytes()
}
func (_MessageParamsVerifregAddVerifier__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"types.MessageParamsVerifregAddVerifier.Repr"}.AsLink()
}
func (_MessageParamsVerifregAddVerifier__Repr) Prototype() ipld.NodePrototype {
	return _MessageParamsVerifregAddVerifier__ReprPrototype{}
}
type _MessageParamsVerifregAddVerifier__ReprPrototype struct{}

func (_MessageParamsVerifregAddVerifier__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _MessageParamsVerifregAddVerifier__ReprBuilder
	nb.Reset()
	return &nb
}
type _MessageParamsVerifregAddVerifier__ReprBuilder struct {
	_MessageParamsVerifregAddVerifier__ReprAssembler
}
func (nb *_MessageParamsVerifregAddVerifier__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MessageParamsVerifregAddVerifier__ReprBuilder) Reset() {
	var w _MessageParamsVerifregAddVerifier
	var m schema.Maybe
	*nb = _MessageParamsVerifregAddVerifier__ReprBuilder{_MessageParamsVerifregAddVerifier__ReprAssembler{w: &w, m: &m}}
}
type _MessageParamsVerifregAddVerifier__ReprAssembler struct {
	w *_MessageParamsVerifregAddVerifier
	m *schema.Maybe
	state laState
	f int

	cm schema.Maybe
	ca_Address _Address__ReprAssembler
	ca_Allowance _BigInt__ReprAssembler
	}

func (na *_MessageParamsVerifregAddVerifier__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_Address.reset()
	na.ca_Allowance.reset()
}
func (_MessageParamsVerifregAddVerifier__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"types.MessageParamsVerifregAddVerifier.Repr"}.BeginMap(0)
}
func (na *_MessageParamsVerifregAddVerifier__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MessageParamsVerifregAddVerifier{}
	}
	return na, nil
}
func (na *_MessageParamsVerifregAddVerifier__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"types.MessageParamsVerifregAddVerifier.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MessageParamsVerifregAddVerifier__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"types.MessageParamsVerifregAddVerifier.Repr"}.AssignBool(false)
}
func (_MessageParamsVerifregAddVerifier__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"types.MessageParamsVerifregAddVerifier.Repr"}.AssignInt(0)
}
func (_MessageParamsVerifregAddVerifier__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"types.MessageParamsVerifregAddVerifier.Repr"}.AssignFloat(0)
}
func (_MessageParamsVerifregAddVerifier__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"types.MessageParamsVerifregAddVerifier.Repr"}.AssignString("")
}
func (_MessageParamsVerifregAddVerifier__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"types.MessageParamsVerifregAddVerifier.Repr"}.AssignBytes(nil)
}
func (_MessageParamsVerifregAddVerifier__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"types.MessageParamsVerifregAddVerifier.Repr"}.AssignLink(nil)
}
func (na *_MessageParamsVerifregAddVerifier__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MessageParamsVerifregAddVerifier); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "types.MessageParamsVerifregAddVerifier.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MessageParamsVerifregAddVerifier__ReprAssembler) Prototype() ipld.NodePrototype {
	return _MessageParamsVerifregAddVerifier__ReprPrototype{}
}
func (la *_MessageParamsVerifregAddVerifier__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 1:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_MessageParamsVerifregAddVerifier__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 2 {
		return nil // schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(2)} // FIXME: need an error thunking assembler!  it has returned.  sigh.
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_Address.w = &la.w.Address
		la.ca_Address.m = &la.cm
		return &la.ca_Address
	case 1:
		la.ca_Allowance.w = &la.w.Allowance
		la.ca_Allowance.m = &la.cm
		return &la.ca_Allowance
	default:
		panic("unreachable")
	}
}
func (la *_MessageParamsVerifregAddVerifier__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_MessageParamsVerifregAddVerifier__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
