package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _MessageParamsMinerTerminateSectors struct {
	Terminations _List__MinerTerminationDecl
}
type MessageParamsMinerTerminateSectors = *_MessageParamsMinerTerminateSectors

func (n _MessageParamsMinerTerminateSectors) FieldTerminations()	List__MinerTerminationDecl {
	return &n.Terminations
}
type _MessageParamsMinerTerminateSectors__Maybe struct {
	m schema.Maybe
	v MessageParamsMinerTerminateSectors
}
type MaybeMessageParamsMinerTerminateSectors = *_MessageParamsMinerTerminateSectors__Maybe

func (m MaybeMessageParamsMinerTerminateSectors) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeMessageParamsMinerTerminateSectors) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeMessageParamsMinerTerminateSectors) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeMessageParamsMinerTerminateSectors) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeMessageParamsMinerTerminateSectors) Must() MessageParamsMinerTerminateSectors {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var (
	fieldName__MessageParamsMinerTerminateSectors_Terminations = _String{"Terminations"}
)
var _ ipld.Node = (MessageParamsMinerTerminateSectors)(&_MessageParamsMinerTerminateSectors{})
var _ schema.TypedNode = (MessageParamsMinerTerminateSectors)(&_MessageParamsMinerTerminateSectors{})
func (MessageParamsMinerTerminateSectors) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n MessageParamsMinerTerminateSectors) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "Terminations":
		return &n.Terminations, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n MessageParamsMinerTerminateSectors) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (MessageParamsMinerTerminateSectors) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.MessageParamsMinerTerminateSectors"}.LookupByIndex(0)
}
func (n MessageParamsMinerTerminateSectors) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n MessageParamsMinerTerminateSectors) MapIterator() ipld.MapIterator {
	return &_MessageParamsMinerTerminateSectors__MapItr{n, 0}
}

type _MessageParamsMinerTerminateSectors__MapItr struct {
	n MessageParamsMinerTerminateSectors
	idx  int
}

func (itr *_MessageParamsMinerTerminateSectors__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 1 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__MessageParamsMinerTerminateSectors_Terminations
		v = &itr.n.Terminations
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MessageParamsMinerTerminateSectors__MapItr) Done() bool {
	return itr.idx >= 1
}

func (MessageParamsMinerTerminateSectors) ListIterator() ipld.ListIterator {
	return nil
}
func (MessageParamsMinerTerminateSectors) Length() int {
	return 1
}
func (MessageParamsMinerTerminateSectors) IsAbsent() bool {
	return false
}
func (MessageParamsMinerTerminateSectors) IsNull() bool {
	return false
}
func (MessageParamsMinerTerminateSectors) AsBool() (bool, error) {
	return mixins.Map{"types.MessageParamsMinerTerminateSectors"}.AsBool()
}
func (MessageParamsMinerTerminateSectors) AsInt() (int, error) {
	return mixins.Map{"types.MessageParamsMinerTerminateSectors"}.AsInt()
}
func (MessageParamsMinerTerminateSectors) AsFloat() (float64, error) {
	return mixins.Map{"types.MessageParamsMinerTerminateSectors"}.AsFloat()
}
func (MessageParamsMinerTerminateSectors) AsString() (string, error) {
	return mixins.Map{"types.MessageParamsMinerTerminateSectors"}.AsString()
}
func (MessageParamsMinerTerminateSectors) AsBytes() ([]byte, error) {
	return mixins.Map{"types.MessageParamsMinerTerminateSectors"}.AsBytes()
}
func (MessageParamsMinerTerminateSectors) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.MessageParamsMinerTerminateSectors"}.AsLink()
}
func (MessageParamsMinerTerminateSectors) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerTerminateSectors__Prototype{}
}
type _MessageParamsMinerTerminateSectors__Prototype struct{}

func (_MessageParamsMinerTerminateSectors__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _MessageParamsMinerTerminateSectors__Builder
	nb.Reset()
	return &nb
}
type _MessageParamsMinerTerminateSectors__Builder struct {
	_MessageParamsMinerTerminateSectors__Assembler
}
func (nb *_MessageParamsMinerTerminateSectors__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MessageParamsMinerTerminateSectors__Builder) Reset() {
	var w _MessageParamsMinerTerminateSectors
	var m schema.Maybe
	*nb = _MessageParamsMinerTerminateSectors__Builder{_MessageParamsMinerTerminateSectors__Assembler{w: &w, m: &m}}
}
type _MessageParamsMinerTerminateSectors__Assembler struct {
	w *_MessageParamsMinerTerminateSectors
	m *schema.Maybe
	state maState
	s int
	f int

	cm schema.Maybe
	ca_Terminations _List__MinerTerminationDecl__Assembler
	}

func (na *_MessageParamsMinerTerminateSectors__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_Terminations.reset()
}

var (
	fieldBit__MessageParamsMinerTerminateSectors_Terminations = 1 << 0
	fieldBits__MessageParamsMinerTerminateSectors_sufficient = 0 + 1 << 0
)
func (na *_MessageParamsMinerTerminateSectors__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MessageParamsMinerTerminateSectors{}
	}
	return na, nil
}
func (_MessageParamsMinerTerminateSectors__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.MessageParamsMinerTerminateSectors"}.BeginList(0)
}
func (na *_MessageParamsMinerTerminateSectors__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.MessageParamsMinerTerminateSectors"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MessageParamsMinerTerminateSectors__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.MessageParamsMinerTerminateSectors"}.AssignBool(false)
}
func (_MessageParamsMinerTerminateSectors__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.MessageParamsMinerTerminateSectors"}.AssignInt(0)
}
func (_MessageParamsMinerTerminateSectors__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.MessageParamsMinerTerminateSectors"}.AssignFloat(0)
}
func (_MessageParamsMinerTerminateSectors__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.MessageParamsMinerTerminateSectors"}.AssignString("")
}
func (_MessageParamsMinerTerminateSectors__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.MessageParamsMinerTerminateSectors"}.AssignBytes(nil)
}
func (_MessageParamsMinerTerminateSectors__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.MessageParamsMinerTerminateSectors"}.AssignLink(nil)
}
func (na *_MessageParamsMinerTerminateSectors__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MessageParamsMinerTerminateSectors); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.MessageParamsMinerTerminateSectors", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MessageParamsMinerTerminateSectors__Assembler) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerTerminateSectors__Prototype{}
}
func (ma *_MessageParamsMinerTerminateSectors__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_Terminations.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_MessageParamsMinerTerminateSectors__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "Terminations":
		if ma.s & fieldBit__MessageParamsMinerTerminateSectors_Terminations != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MessageParamsMinerTerminateSectors_Terminations}
		}
		ma.s += fieldBit__MessageParamsMinerTerminateSectors_Terminations
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_Terminations.w = &ma.w.Terminations
		ma.ca_Terminations.m = &ma.cm
		return &ma.ca_Terminations, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName:"types.MessageParamsMinerTerminateSectors", Key:&_String{k}}
	}
}
func (ma *_MessageParamsMinerTerminateSectors__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_MessageParamsMinerTerminateSectors__KeyAssembler)(ma)
}
func (ma *_MessageParamsMinerTerminateSectors__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_Terminations.w = &ma.w.Terminations
		ma.ca_Terminations.m = &ma.cm
		return &ma.ca_Terminations
	default:
		panic("unreachable")
	}
}
func (ma *_MessageParamsMinerTerminateSectors__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_MessageParamsMinerTerminateSectors__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_MessageParamsMinerTerminateSectors__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}
type _MessageParamsMinerTerminateSectors__KeyAssembler _MessageParamsMinerTerminateSectors__Assembler
func (_MessageParamsMinerTerminateSectors__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"types.MessageParamsMinerTerminateSectors.KeyAssembler"}.BeginMap(0)
}
func (_MessageParamsMinerTerminateSectors__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"types.MessageParamsMinerTerminateSectors.KeyAssembler"}.BeginList(0)
}
func (na *_MessageParamsMinerTerminateSectors__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"types.MessageParamsMinerTerminateSectors.KeyAssembler"}.AssignNull()
}
func (_MessageParamsMinerTerminateSectors__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"types.MessageParamsMinerTerminateSectors.KeyAssembler"}.AssignBool(false)
}
func (_MessageParamsMinerTerminateSectors__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"types.MessageParamsMinerTerminateSectors.KeyAssembler"}.AssignInt(0)
}
func (_MessageParamsMinerTerminateSectors__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"types.MessageParamsMinerTerminateSectors.KeyAssembler"}.AssignFloat(0)
}
func (ka *_MessageParamsMinerTerminateSectors__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "Terminations":
		if ka.s & fieldBit__MessageParamsMinerTerminateSectors_Terminations != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MessageParamsMinerTerminateSectors_Terminations}
		}
		ka.s += fieldBit__MessageParamsMinerTerminateSectors_Terminations
		ka.state = maState_expectValue
		ka.f = 0
	default:
		return ipld.ErrInvalidKey{TypeName:"types.MessageParamsMinerTerminateSectors", Key:&_String{k}}
	}
	return nil
}
func (_MessageParamsMinerTerminateSectors__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"types.MessageParamsMinerTerminateSectors.KeyAssembler"}.AssignBytes(nil)
}
func (_MessageParamsMinerTerminateSectors__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"types.MessageParamsMinerTerminateSectors.KeyAssembler"}.AssignLink(nil)
}
func (ka *_MessageParamsMinerTerminateSectors__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_MessageParamsMinerTerminateSectors__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (MessageParamsMinerTerminateSectors) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n MessageParamsMinerTerminateSectors) Representation() ipld.Node {
	return (*_MessageParamsMinerTerminateSectors__Repr)(n)
}
type _MessageParamsMinerTerminateSectors__Repr _MessageParamsMinerTerminateSectors
var _ ipld.Node = &_MessageParamsMinerTerminateSectors__Repr{}
func (_MessageParamsMinerTerminateSectors__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_MessageParamsMinerTerminateSectors__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"types.MessageParamsMinerTerminateSectors.Repr"}.LookupByString("")
}
func (n *_MessageParamsMinerTerminateSectors__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_MessageParamsMinerTerminateSectors__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.Terminations.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _MessageParamsMinerTerminateSectors__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "types.MessageParamsMinerTerminateSectors.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_MessageParamsMinerTerminateSectors__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_MessageParamsMinerTerminateSectors__Repr) ListIterator() ipld.ListIterator {
	return &_MessageParamsMinerTerminateSectors__ReprListItr{n, 0}
}

type _MessageParamsMinerTerminateSectors__ReprListItr struct {
	n   *_MessageParamsMinerTerminateSectors__Repr
	idx int
	
}

func (itr *_MessageParamsMinerTerminateSectors__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 1 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.Terminations.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MessageParamsMinerTerminateSectors__ReprListItr) Done() bool {
	return itr.idx >= 1
}

func (rn *_MessageParamsMinerTerminateSectors__Repr) Length() int {
	l := 1
	return l
}
func (_MessageParamsMinerTerminateSectors__Repr) IsAbsent() bool {
	return false
}
func (_MessageParamsMinerTerminateSectors__Repr) IsNull() bool {
	return false
}
func (_MessageParamsMinerTerminateSectors__Repr) AsBool() (bool, error) {
	return mixins.List{"types.MessageParamsMinerTerminateSectors.Repr"}.AsBool()
}
func (_MessageParamsMinerTerminateSectors__Repr) AsInt() (int, error) {
	return mixins.List{"types.MessageParamsMinerTerminateSectors.Repr"}.AsInt()
}
func (_MessageParamsMinerTerminateSectors__Repr) AsFloat() (float64, error) {
	return mixins.List{"types.MessageParamsMinerTerminateSectors.Repr"}.AsFloat()
}
func (_MessageParamsMinerTerminateSectors__Repr) AsString() (string, error) {
	return mixins.List{"types.MessageParamsMinerTerminateSectors.Repr"}.AsString()
}
func (_MessageParamsMinerTerminateSectors__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"types.MessageParamsMinerTerminateSectors.Repr"}.AsBytes()
}
func (_MessageParamsMinerTerminateSectors__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"types.MessageParamsMinerTerminateSectors.Repr"}.AsLink()
}
func (_MessageParamsMinerTerminateSectors__Repr) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerTerminateSectors__ReprPrototype{}
}
type _MessageParamsMinerTerminateSectors__ReprPrototype struct{}

func (_MessageParamsMinerTerminateSectors__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _MessageParamsMinerTerminateSectors__ReprBuilder
	nb.Reset()
	return &nb
}
type _MessageParamsMinerTerminateSectors__ReprBuilder struct {
	_MessageParamsMinerTerminateSectors__ReprAssembler
}
func (nb *_MessageParamsMinerTerminateSectors__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MessageParamsMinerTerminateSectors__ReprBuilder) Reset() {
	var w _MessageParamsMinerTerminateSectors
	var m schema.Maybe
	*nb = _MessageParamsMinerTerminateSectors__ReprBuilder{_MessageParamsMinerTerminateSectors__ReprAssembler{w: &w, m: &m}}
}
type _MessageParamsMinerTerminateSectors__ReprAssembler struct {
	w *_MessageParamsMinerTerminateSectors
	m *schema.Maybe
	state laState
	f int

	cm schema.Maybe
	ca_Terminations _List__MinerTerminationDecl__ReprAssembler
	}

func (na *_MessageParamsMinerTerminateSectors__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_Terminations.reset()
}
func (_MessageParamsMinerTerminateSectors__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"types.MessageParamsMinerTerminateSectors.Repr"}.BeginMap(0)
}
func (na *_MessageParamsMinerTerminateSectors__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MessageParamsMinerTerminateSectors{}
	}
	return na, nil
}
func (na *_MessageParamsMinerTerminateSectors__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"types.MessageParamsMinerTerminateSectors.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MessageParamsMinerTerminateSectors__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"types.MessageParamsMinerTerminateSectors.Repr"}.AssignBool(false)
}
func (_MessageParamsMinerTerminateSectors__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"types.MessageParamsMinerTerminateSectors.Repr"}.AssignInt(0)
}
func (_MessageParamsMinerTerminateSectors__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"types.MessageParamsMinerTerminateSectors.Repr"}.AssignFloat(0)
}
func (_MessageParamsMinerTerminateSectors__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"types.MessageParamsMinerTerminateSectors.Repr"}.AssignString("")
}
func (_MessageParamsMinerTerminateSectors__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"types.MessageParamsMinerTerminateSectors.Repr"}.AssignBytes(nil)
}
func (_MessageParamsMinerTerminateSectors__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"types.MessageParamsMinerTerminateSectors.Repr"}.AssignLink(nil)
}
func (na *_MessageParamsMinerTerminateSectors__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MessageParamsMinerTerminateSectors); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "types.MessageParamsMinerTerminateSectors.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MessageParamsMinerTerminateSectors__ReprAssembler) Prototype() ipld.NodePrototype {
	return _MessageParamsMinerTerminateSectors__ReprPrototype{}
}
func (la *_MessageParamsMinerTerminateSectors__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_MessageParamsMinerTerminateSectors__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 1 {
		return _ErrorThunkAssembler{schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(1)}}
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_Terminations.w = &la.w.Terminations
		la.ca_Terminations.m = &la.cm
		return &la.ca_Terminations
	default:
		panic("unreachable")
	}
}
func (la *_MessageParamsMinerTerminateSectors__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_MessageParamsMinerTerminateSectors__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
