package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _MinerV0VestingFunds struct {
	Funds _List__MinerV0VestingFund
}
type MinerV0VestingFunds = *_MinerV0VestingFunds

func (n _MinerV0VestingFunds) FieldFunds()	List__MinerV0VestingFund {
	return &n.Funds
}
type _MinerV0VestingFunds__Maybe struct {
	m schema.Maybe
	v MinerV0VestingFunds
}
type MaybeMinerV0VestingFunds = *_MinerV0VestingFunds__Maybe

func (m MaybeMinerV0VestingFunds) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeMinerV0VestingFunds) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeMinerV0VestingFunds) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeMinerV0VestingFunds) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeMinerV0VestingFunds) Must() MinerV0VestingFunds {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var (
	fieldName__MinerV0VestingFunds_Funds = _String{"Funds"}
)
var _ ipld.Node = (MinerV0VestingFunds)(&_MinerV0VestingFunds{})
var _ schema.TypedNode = (MinerV0VestingFunds)(&_MinerV0VestingFunds{})
func (MinerV0VestingFunds) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n MinerV0VestingFunds) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "Funds":
		return &n.Funds, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n MinerV0VestingFunds) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (MinerV0VestingFunds) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.MinerV0VestingFunds"}.LookupByIndex(0)
}
func (n MinerV0VestingFunds) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n MinerV0VestingFunds) MapIterator() ipld.MapIterator {
	return &_MinerV0VestingFunds__MapItr{n, 0}
}

type _MinerV0VestingFunds__MapItr struct {
	n MinerV0VestingFunds
	idx  int
}

func (itr *_MinerV0VestingFunds__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 1 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__MinerV0VestingFunds_Funds
		v = &itr.n.Funds
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MinerV0VestingFunds__MapItr) Done() bool {
	return itr.idx >= 1
}

func (MinerV0VestingFunds) ListIterator() ipld.ListIterator {
	return nil
}
func (MinerV0VestingFunds) Length() int {
	return 1
}
func (MinerV0VestingFunds) IsAbsent() bool {
	return false
}
func (MinerV0VestingFunds) IsNull() bool {
	return false
}
func (MinerV0VestingFunds) AsBool() (bool, error) {
	return mixins.Map{"types.MinerV0VestingFunds"}.AsBool()
}
func (MinerV0VestingFunds) AsInt() (int, error) {
	return mixins.Map{"types.MinerV0VestingFunds"}.AsInt()
}
func (MinerV0VestingFunds) AsFloat() (float64, error) {
	return mixins.Map{"types.MinerV0VestingFunds"}.AsFloat()
}
func (MinerV0VestingFunds) AsString() (string, error) {
	return mixins.Map{"types.MinerV0VestingFunds"}.AsString()
}
func (MinerV0VestingFunds) AsBytes() ([]byte, error) {
	return mixins.Map{"types.MinerV0VestingFunds"}.AsBytes()
}
func (MinerV0VestingFunds) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.MinerV0VestingFunds"}.AsLink()
}
func (MinerV0VestingFunds) Prototype() ipld.NodePrototype {
	return _MinerV0VestingFunds__Prototype{}
}
type _MinerV0VestingFunds__Prototype struct{}

func (_MinerV0VestingFunds__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _MinerV0VestingFunds__Builder
	nb.Reset()
	return &nb
}
type _MinerV0VestingFunds__Builder struct {
	_MinerV0VestingFunds__Assembler
}
func (nb *_MinerV0VestingFunds__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MinerV0VestingFunds__Builder) Reset() {
	var w _MinerV0VestingFunds
	var m schema.Maybe
	*nb = _MinerV0VestingFunds__Builder{_MinerV0VestingFunds__Assembler{w: &w, m: &m}}
}
type _MinerV0VestingFunds__Assembler struct {
	w *_MinerV0VestingFunds
	m *schema.Maybe
	state maState
	s int
	f int

	cm schema.Maybe
	ca_Funds _List__MinerV0VestingFund__Assembler
	}

func (na *_MinerV0VestingFunds__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_Funds.reset()
}

var (
	fieldBit__MinerV0VestingFunds_Funds = 1 << 0
	fieldBits__MinerV0VestingFunds_sufficient = 0 + 1 << 0
)
func (na *_MinerV0VestingFunds__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MinerV0VestingFunds{}
	}
	return na, nil
}
func (_MinerV0VestingFunds__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.MinerV0VestingFunds"}.BeginList(0)
}
func (na *_MinerV0VestingFunds__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.MinerV0VestingFunds"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MinerV0VestingFunds__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.MinerV0VestingFunds"}.AssignBool(false)
}
func (_MinerV0VestingFunds__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.MinerV0VestingFunds"}.AssignInt(0)
}
func (_MinerV0VestingFunds__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.MinerV0VestingFunds"}.AssignFloat(0)
}
func (_MinerV0VestingFunds__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.MinerV0VestingFunds"}.AssignString("")
}
func (_MinerV0VestingFunds__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.MinerV0VestingFunds"}.AssignBytes(nil)
}
func (_MinerV0VestingFunds__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.MinerV0VestingFunds"}.AssignLink(nil)
}
func (na *_MinerV0VestingFunds__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MinerV0VestingFunds); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.MinerV0VestingFunds", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MinerV0VestingFunds__Assembler) Prototype() ipld.NodePrototype {
	return _MinerV0VestingFunds__Prototype{}
}
func (ma *_MinerV0VestingFunds__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_Funds.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_MinerV0VestingFunds__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "Funds":
		if ma.s & fieldBit__MinerV0VestingFunds_Funds != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MinerV0VestingFunds_Funds}
		}
		ma.s += fieldBit__MinerV0VestingFunds_Funds
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_Funds.w = &ma.w.Funds
		ma.ca_Funds.m = &ma.cm
		return &ma.ca_Funds, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName:"types.MinerV0VestingFunds", Key:&_String{k}}
	}
}
func (ma *_MinerV0VestingFunds__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_MinerV0VestingFunds__KeyAssembler)(ma)
}
func (ma *_MinerV0VestingFunds__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_Funds.w = &ma.w.Funds
		ma.ca_Funds.m = &ma.cm
		return &ma.ca_Funds
	default:
		panic("unreachable")
	}
}
func (ma *_MinerV0VestingFunds__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_MinerV0VestingFunds__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_MinerV0VestingFunds__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}
type _MinerV0VestingFunds__KeyAssembler _MinerV0VestingFunds__Assembler
func (_MinerV0VestingFunds__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"types.MinerV0VestingFunds.KeyAssembler"}.BeginMap(0)
}
func (_MinerV0VestingFunds__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"types.MinerV0VestingFunds.KeyAssembler"}.BeginList(0)
}
func (na *_MinerV0VestingFunds__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"types.MinerV0VestingFunds.KeyAssembler"}.AssignNull()
}
func (_MinerV0VestingFunds__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"types.MinerV0VestingFunds.KeyAssembler"}.AssignBool(false)
}
func (_MinerV0VestingFunds__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"types.MinerV0VestingFunds.KeyAssembler"}.AssignInt(0)
}
func (_MinerV0VestingFunds__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"types.MinerV0VestingFunds.KeyAssembler"}.AssignFloat(0)
}
func (ka *_MinerV0VestingFunds__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "Funds":
		if ka.s & fieldBit__MinerV0VestingFunds_Funds != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MinerV0VestingFunds_Funds}
		}
		ka.s += fieldBit__MinerV0VestingFunds_Funds
		ka.state = maState_expectValue
		ka.f = 0
	default:
		return ipld.ErrInvalidKey{TypeName:"types.MinerV0VestingFunds", Key:&_String{k}}
	}
	return nil
}
func (_MinerV0VestingFunds__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"types.MinerV0VestingFunds.KeyAssembler"}.AssignBytes(nil)
}
func (_MinerV0VestingFunds__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"types.MinerV0VestingFunds.KeyAssembler"}.AssignLink(nil)
}
func (ka *_MinerV0VestingFunds__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_MinerV0VestingFunds__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (MinerV0VestingFunds) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n MinerV0VestingFunds) Representation() ipld.Node {
	return (*_MinerV0VestingFunds__Repr)(n)
}
type _MinerV0VestingFunds__Repr _MinerV0VestingFunds
var _ ipld.Node = &_MinerV0VestingFunds__Repr{}
func (_MinerV0VestingFunds__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_MinerV0VestingFunds__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"types.MinerV0VestingFunds.Repr"}.LookupByString("")
}
func (n *_MinerV0VestingFunds__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_MinerV0VestingFunds__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.Funds.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _MinerV0VestingFunds__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "types.MinerV0VestingFunds.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_MinerV0VestingFunds__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_MinerV0VestingFunds__Repr) ListIterator() ipld.ListIterator {
	return &_MinerV0VestingFunds__ReprListItr{n, 0}
}

type _MinerV0VestingFunds__ReprListItr struct {
	n   *_MinerV0VestingFunds__Repr
	idx int
	
}

func (itr *_MinerV0VestingFunds__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 1 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.Funds.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MinerV0VestingFunds__ReprListItr) Done() bool {
	return itr.idx >= 1
}

func (rn *_MinerV0VestingFunds__Repr) Length() int {
	l := 1
	return l
}
func (_MinerV0VestingFunds__Repr) IsAbsent() bool {
	return false
}
func (_MinerV0VestingFunds__Repr) IsNull() bool {
	return false
}
func (_MinerV0VestingFunds__Repr) AsBool() (bool, error) {
	return mixins.List{"types.MinerV0VestingFunds.Repr"}.AsBool()
}
func (_MinerV0VestingFunds__Repr) AsInt() (int, error) {
	return mixins.List{"types.MinerV0VestingFunds.Repr"}.AsInt()
}
func (_MinerV0VestingFunds__Repr) AsFloat() (float64, error) {
	return mixins.List{"types.MinerV0VestingFunds.Repr"}.AsFloat()
}
func (_MinerV0VestingFunds__Repr) AsString() (string, error) {
	return mixins.List{"types.MinerV0VestingFunds.Repr"}.AsString()
}
func (_MinerV0VestingFunds__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"types.MinerV0VestingFunds.Repr"}.AsBytes()
}
func (_MinerV0VestingFunds__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"types.MinerV0VestingFunds.Repr"}.AsLink()
}
func (_MinerV0VestingFunds__Repr) Prototype() ipld.NodePrototype {
	return _MinerV0VestingFunds__ReprPrototype{}
}
type _MinerV0VestingFunds__ReprPrototype struct{}

func (_MinerV0VestingFunds__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _MinerV0VestingFunds__ReprBuilder
	nb.Reset()
	return &nb
}
type _MinerV0VestingFunds__ReprBuilder struct {
	_MinerV0VestingFunds__ReprAssembler
}
func (nb *_MinerV0VestingFunds__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MinerV0VestingFunds__ReprBuilder) Reset() {
	var w _MinerV0VestingFunds
	var m schema.Maybe
	*nb = _MinerV0VestingFunds__ReprBuilder{_MinerV0VestingFunds__ReprAssembler{w: &w, m: &m}}
}
type _MinerV0VestingFunds__ReprAssembler struct {
	w *_MinerV0VestingFunds
	m *schema.Maybe
	state laState
	f int

	cm schema.Maybe
	ca_Funds _List__MinerV0VestingFund__ReprAssembler
	}

func (na *_MinerV0VestingFunds__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_Funds.reset()
}
func (_MinerV0VestingFunds__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"types.MinerV0VestingFunds.Repr"}.BeginMap(0)
}
func (na *_MinerV0VestingFunds__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MinerV0VestingFunds{}
	}
	return na, nil
}
func (na *_MinerV0VestingFunds__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"types.MinerV0VestingFunds.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MinerV0VestingFunds__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"types.MinerV0VestingFunds.Repr"}.AssignBool(false)
}
func (_MinerV0VestingFunds__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"types.MinerV0VestingFunds.Repr"}.AssignInt(0)
}
func (_MinerV0VestingFunds__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"types.MinerV0VestingFunds.Repr"}.AssignFloat(0)
}
func (_MinerV0VestingFunds__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"types.MinerV0VestingFunds.Repr"}.AssignString("")
}
func (_MinerV0VestingFunds__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"types.MinerV0VestingFunds.Repr"}.AssignBytes(nil)
}
func (_MinerV0VestingFunds__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"types.MinerV0VestingFunds.Repr"}.AssignLink(nil)
}
func (na *_MinerV0VestingFunds__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MinerV0VestingFunds); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "types.MinerV0VestingFunds.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MinerV0VestingFunds__ReprAssembler) Prototype() ipld.NodePrototype {
	return _MinerV0VestingFunds__ReprPrototype{}
}
func (la *_MinerV0VestingFunds__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_MinerV0VestingFunds__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 1 {
		return _ErrorThunkAssembler{schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(1)}}
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_Funds.w = &la.w.Funds
		la.ca_Funds.m = &la.cm
		return &la.ca_Funds
	default:
		panic("unreachable")
	}
}
func (la *_MinerV0VestingFunds__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_MinerV0VestingFunds__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
