package types

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
	"github.com/ipld/go-ipld-prime/node/mixins"
	"github.com/ipld/go-ipld-prime/schema"
)

type _MinerV0ExpirationSet struct {
	OnTimeSectors _BitField
	EarlySectors _BitField
	OnTimePledge _BigInt
	ActivePower _MinerV0PowerPair
	FaultyPower _MinerV0PowerPair
}
type MinerV0ExpirationSet = *_MinerV0ExpirationSet

func (n _MinerV0ExpirationSet) FieldOnTimeSectors()	BitField {
	return &n.OnTimeSectors
}
func (n _MinerV0ExpirationSet) FieldEarlySectors()	BitField {
	return &n.EarlySectors
}
func (n _MinerV0ExpirationSet) FieldOnTimePledge()	BigInt {
	return &n.OnTimePledge
}
func (n _MinerV0ExpirationSet) FieldActivePower()	MinerV0PowerPair {
	return &n.ActivePower
}
func (n _MinerV0ExpirationSet) FieldFaultyPower()	MinerV0PowerPair {
	return &n.FaultyPower
}
type _MinerV0ExpirationSet__Maybe struct {
	m schema.Maybe
	v MinerV0ExpirationSet
}
type MaybeMinerV0ExpirationSet = *_MinerV0ExpirationSet__Maybe

func (m MaybeMinerV0ExpirationSet) IsNull() bool {
	return m.m == schema.Maybe_Null
}
func (m MaybeMinerV0ExpirationSet) IsAbsent() bool {
	return m.m == schema.Maybe_Absent
}
func (m MaybeMinerV0ExpirationSet) Exists() bool {
	return m.m == schema.Maybe_Value
}
func (m MaybeMinerV0ExpirationSet) AsNode() ipld.Node {
	switch m.m {
		case schema.Maybe_Absent:
			return ipld.Absent
		case schema.Maybe_Null:
			return ipld.Null
		case schema.Maybe_Value:
			return m.v
		default:
			panic("unreachable")
	}
}
func (m MaybeMinerV0ExpirationSet) Must() MinerV0ExpirationSet {
	if !m.Exists() {
		panic("unbox of a maybe rejected")
	}
	return m.v
}
var (
	fieldName__MinerV0ExpirationSet_OnTimeSectors = _String{"OnTimeSectors"}
	fieldName__MinerV0ExpirationSet_EarlySectors = _String{"EarlySectors"}
	fieldName__MinerV0ExpirationSet_OnTimePledge = _String{"OnTimePledge"}
	fieldName__MinerV0ExpirationSet_ActivePower = _String{"ActivePower"}
	fieldName__MinerV0ExpirationSet_FaultyPower = _String{"FaultyPower"}
)
var _ ipld.Node = (MinerV0ExpirationSet)(&_MinerV0ExpirationSet{})
var _ schema.TypedNode = (MinerV0ExpirationSet)(&_MinerV0ExpirationSet{})
func (MinerV0ExpirationSet) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_Map
}
func (n MinerV0ExpirationSet) LookupByString(key string) (ipld.Node, error) {
	switch key {
	case "OnTimeSectors":
		return &n.OnTimeSectors, nil
	case "EarlySectors":
		return &n.EarlySectors, nil
	case "OnTimePledge":
		return &n.OnTimePledge, nil
	case "ActivePower":
		return &n.ActivePower, nil
	case "FaultyPower":
		return &n.FaultyPower, nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfString(key)}
	}
}
func (n MinerV0ExpirationSet) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ks, err := key.AsString()
	if err != nil {
		return nil, err
	}
	return n.LookupByString(ks)
}
func (MinerV0ExpirationSet) LookupByIndex(idx int) (ipld.Node, error) {
	return mixins.Map{"types.MinerV0ExpirationSet"}.LookupByIndex(0)
}
func (n MinerV0ExpirationSet) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	return n.LookupByString(seg.String())
}
func (n MinerV0ExpirationSet) MapIterator() ipld.MapIterator {
	return &_MinerV0ExpirationSet__MapItr{n, 0}
}

type _MinerV0ExpirationSet__MapItr struct {
	n MinerV0ExpirationSet
	idx  int
}

func (itr *_MinerV0ExpirationSet__MapItr) Next() (k ipld.Node, v ipld.Node, _ error) {
	if itr.idx >= 5 {
		return nil, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		k = &fieldName__MinerV0ExpirationSet_OnTimeSectors
		v = &itr.n.OnTimeSectors
	case 1:
		k = &fieldName__MinerV0ExpirationSet_EarlySectors
		v = &itr.n.EarlySectors
	case 2:
		k = &fieldName__MinerV0ExpirationSet_OnTimePledge
		v = &itr.n.OnTimePledge
	case 3:
		k = &fieldName__MinerV0ExpirationSet_ActivePower
		v = &itr.n.ActivePower
	case 4:
		k = &fieldName__MinerV0ExpirationSet_FaultyPower
		v = &itr.n.FaultyPower
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MinerV0ExpirationSet__MapItr) Done() bool {
	return itr.idx >= 5
}

func (MinerV0ExpirationSet) ListIterator() ipld.ListIterator {
	return nil
}
func (MinerV0ExpirationSet) Length() int {
	return 5
}
func (MinerV0ExpirationSet) IsAbsent() bool {
	return false
}
func (MinerV0ExpirationSet) IsNull() bool {
	return false
}
func (MinerV0ExpirationSet) AsBool() (bool, error) {
	return mixins.Map{"types.MinerV0ExpirationSet"}.AsBool()
}
func (MinerV0ExpirationSet) AsInt() (int, error) {
	return mixins.Map{"types.MinerV0ExpirationSet"}.AsInt()
}
func (MinerV0ExpirationSet) AsFloat() (float64, error) {
	return mixins.Map{"types.MinerV0ExpirationSet"}.AsFloat()
}
func (MinerV0ExpirationSet) AsString() (string, error) {
	return mixins.Map{"types.MinerV0ExpirationSet"}.AsString()
}
func (MinerV0ExpirationSet) AsBytes() ([]byte, error) {
	return mixins.Map{"types.MinerV0ExpirationSet"}.AsBytes()
}
func (MinerV0ExpirationSet) AsLink() (ipld.Link, error) {
	return mixins.Map{"types.MinerV0ExpirationSet"}.AsLink()
}
func (MinerV0ExpirationSet) Prototype() ipld.NodePrototype {
	return _MinerV0ExpirationSet__Prototype{}
}
type _MinerV0ExpirationSet__Prototype struct{}

func (_MinerV0ExpirationSet__Prototype) NewBuilder() ipld.NodeBuilder {
	var nb _MinerV0ExpirationSet__Builder
	nb.Reset()
	return &nb
}
type _MinerV0ExpirationSet__Builder struct {
	_MinerV0ExpirationSet__Assembler
}
func (nb *_MinerV0ExpirationSet__Builder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MinerV0ExpirationSet__Builder) Reset() {
	var w _MinerV0ExpirationSet
	var m schema.Maybe
	*nb = _MinerV0ExpirationSet__Builder{_MinerV0ExpirationSet__Assembler{w: &w, m: &m}}
}
type _MinerV0ExpirationSet__Assembler struct {
	w *_MinerV0ExpirationSet
	m *schema.Maybe
	state maState
	s int
	f int

	cm schema.Maybe
	ca_OnTimeSectors _BitField__Assembler
	ca_EarlySectors _BitField__Assembler
	ca_OnTimePledge _BigInt__Assembler
	ca_ActivePower _MinerV0PowerPair__Assembler
	ca_FaultyPower _MinerV0PowerPair__Assembler
	}

func (na *_MinerV0ExpirationSet__Assembler) reset() {
	na.state = maState_initial
	na.s = 0
	na.ca_OnTimeSectors.reset()
	na.ca_EarlySectors.reset()
	na.ca_OnTimePledge.reset()
	na.ca_ActivePower.reset()
	na.ca_FaultyPower.reset()
}

var (
	fieldBit__MinerV0ExpirationSet_OnTimeSectors = 1 << 0
	fieldBit__MinerV0ExpirationSet_EarlySectors = 1 << 1
	fieldBit__MinerV0ExpirationSet_OnTimePledge = 1 << 2
	fieldBit__MinerV0ExpirationSet_ActivePower = 1 << 3
	fieldBit__MinerV0ExpirationSet_FaultyPower = 1 << 4
	fieldBits__MinerV0ExpirationSet_sufficient = 0 + 1 << 0 + 1 << 1 + 1 << 2 + 1 << 3 + 1 << 4
)
func (na *_MinerV0ExpirationSet__Assembler) BeginMap(int) (ipld.MapAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MinerV0ExpirationSet{}
	}
	return na, nil
}
func (_MinerV0ExpirationSet__Assembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.MapAssembler{"types.MinerV0ExpirationSet"}.BeginList(0)
}
func (na *_MinerV0ExpirationSet__Assembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.MapAssembler{"types.MinerV0ExpirationSet"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MinerV0ExpirationSet__Assembler) AssignBool(bool) error {
	return mixins.MapAssembler{"types.MinerV0ExpirationSet"}.AssignBool(false)
}
func (_MinerV0ExpirationSet__Assembler) AssignInt(int) error {
	return mixins.MapAssembler{"types.MinerV0ExpirationSet"}.AssignInt(0)
}
func (_MinerV0ExpirationSet__Assembler) AssignFloat(float64) error {
	return mixins.MapAssembler{"types.MinerV0ExpirationSet"}.AssignFloat(0)
}
func (_MinerV0ExpirationSet__Assembler) AssignString(string) error {
	return mixins.MapAssembler{"types.MinerV0ExpirationSet"}.AssignString("")
}
func (_MinerV0ExpirationSet__Assembler) AssignBytes([]byte) error {
	return mixins.MapAssembler{"types.MinerV0ExpirationSet"}.AssignBytes(nil)
}
func (_MinerV0ExpirationSet__Assembler) AssignLink(ipld.Link) error {
	return mixins.MapAssembler{"types.MinerV0ExpirationSet"}.AssignLink(nil)
}
func (na *_MinerV0ExpirationSet__Assembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MinerV0ExpirationSet); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_Map {
		return ipld.ErrWrongKind{TypeName: "types.MinerV0ExpirationSet", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustMap, ActualKind: v.ReprKind()}
	}
	itr := v.MapIterator()
	for !itr.Done() {
		k, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleKey().AssignNode(k); err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MinerV0ExpirationSet__Assembler) Prototype() ipld.NodePrototype {
	return _MinerV0ExpirationSet__Prototype{}
}
func (ma *_MinerV0ExpirationSet__Assembler) valueFinishTidy() bool {
	switch ma.f {
	case 0:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_OnTimeSectors.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 1:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_EarlySectors.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 2:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_OnTimePledge.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 3:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_ActivePower.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	case 4:
		switch ma.cm {
		case schema.Maybe_Value:
			ma.ca_FaultyPower.w = nil
			ma.cm = schema.Maybe_Absent
			ma.state = maState_initial
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (ma *_MinerV0ExpirationSet__Assembler) AssembleEntry(k string) (ipld.NodeAssembler, error) {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleEntry cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleEntry cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleEntry cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleEntry cannot be called on an assembler that's already finished")
	}
	switch k {
	case "OnTimeSectors":
		if ma.s & fieldBit__MinerV0ExpirationSet_OnTimeSectors != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MinerV0ExpirationSet_OnTimeSectors}
		}
		ma.s += fieldBit__MinerV0ExpirationSet_OnTimeSectors
		ma.state = maState_midValue
		ma.f = 0
		ma.ca_OnTimeSectors.w = &ma.w.OnTimeSectors
		ma.ca_OnTimeSectors.m = &ma.cm
		return &ma.ca_OnTimeSectors, nil
	case "EarlySectors":
		if ma.s & fieldBit__MinerV0ExpirationSet_EarlySectors != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MinerV0ExpirationSet_EarlySectors}
		}
		ma.s += fieldBit__MinerV0ExpirationSet_EarlySectors
		ma.state = maState_midValue
		ma.f = 1
		ma.ca_EarlySectors.w = &ma.w.EarlySectors
		ma.ca_EarlySectors.m = &ma.cm
		return &ma.ca_EarlySectors, nil
	case "OnTimePledge":
		if ma.s & fieldBit__MinerV0ExpirationSet_OnTimePledge != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MinerV0ExpirationSet_OnTimePledge}
		}
		ma.s += fieldBit__MinerV0ExpirationSet_OnTimePledge
		ma.state = maState_midValue
		ma.f = 2
		ma.ca_OnTimePledge.w = &ma.w.OnTimePledge
		ma.ca_OnTimePledge.m = &ma.cm
		return &ma.ca_OnTimePledge, nil
	case "ActivePower":
		if ma.s & fieldBit__MinerV0ExpirationSet_ActivePower != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MinerV0ExpirationSet_ActivePower}
		}
		ma.s += fieldBit__MinerV0ExpirationSet_ActivePower
		ma.state = maState_midValue
		ma.f = 3
		ma.ca_ActivePower.w = &ma.w.ActivePower
		ma.ca_ActivePower.m = &ma.cm
		return &ma.ca_ActivePower, nil
	case "FaultyPower":
		if ma.s & fieldBit__MinerV0ExpirationSet_FaultyPower != 0 {
			return nil, ipld.ErrRepeatedMapKey{&fieldName__MinerV0ExpirationSet_FaultyPower}
		}
		ma.s += fieldBit__MinerV0ExpirationSet_FaultyPower
		ma.state = maState_midValue
		ma.f = 4
		ma.ca_FaultyPower.w = &ma.w.FaultyPower
		ma.ca_FaultyPower.m = &ma.cm
		return &ma.ca_FaultyPower, nil
	default:
		return nil, ipld.ErrInvalidKey{TypeName:"types.MinerV0ExpirationSet", Key:&_String{k}}
	}
}
func (ma *_MinerV0ExpirationSet__Assembler) AssembleKey() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: AssembleKey cannot be called when in the middle of assembling another key")
	case maState_expectValue:
		panic("invalid state: AssembleKey cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: AssembleKey cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: AssembleKey cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midKey
	return (*_MinerV0ExpirationSet__KeyAssembler)(ma)
}
func (ma *_MinerV0ExpirationSet__Assembler) AssembleValue() ipld.NodeAssembler {
	switch ma.state {
	case maState_initial:
		panic("invalid state: AssembleValue cannot be called when no key is primed")
	case maState_midKey:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		// carry on
	case maState_midValue:
		panic("invalid state: AssembleValue cannot be called when in the middle of assembling another value")
	case maState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	ma.state = maState_midValue
	switch ma.f {
	case 0:
		ma.ca_OnTimeSectors.w = &ma.w.OnTimeSectors
		ma.ca_OnTimeSectors.m = &ma.cm
		return &ma.ca_OnTimeSectors
	case 1:
		ma.ca_EarlySectors.w = &ma.w.EarlySectors
		ma.ca_EarlySectors.m = &ma.cm
		return &ma.ca_EarlySectors
	case 2:
		ma.ca_OnTimePledge.w = &ma.w.OnTimePledge
		ma.ca_OnTimePledge.m = &ma.cm
		return &ma.ca_OnTimePledge
	case 3:
		ma.ca_ActivePower.w = &ma.w.ActivePower
		ma.ca_ActivePower.m = &ma.cm
		return &ma.ca_ActivePower
	case 4:
		ma.ca_FaultyPower.w = &ma.w.FaultyPower
		ma.ca_FaultyPower.m = &ma.cm
		return &ma.ca_FaultyPower
	default:
		panic("unreachable")
	}
}
func (ma *_MinerV0ExpirationSet__Assembler) Finish() error {
	switch ma.state {
	case maState_initial:
		// carry on
	case maState_midKey:
		panic("invalid state: Finish cannot be called when in the middle of assembling a key")
	case maState_expectValue:
		panic("invalid state: Finish cannot be called when expecting start of value assembly")
	case maState_midValue:
		if !ma.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case maState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	//FIXME check if all required fields are set
	ma.state = maState_finished
	*ma.m = schema.Maybe_Value
	return nil
}
func (ma *_MinerV0ExpirationSet__Assembler) KeyPrototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (ma *_MinerV0ExpirationSet__Assembler) ValuePrototype(k string) ipld.NodePrototype {
	panic("todo structbuilder mapassembler valueprototype")
}
type _MinerV0ExpirationSet__KeyAssembler _MinerV0ExpirationSet__Assembler
func (_MinerV0ExpirationSet__KeyAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.StringAssembler{"types.MinerV0ExpirationSet.KeyAssembler"}.BeginMap(0)
}
func (_MinerV0ExpirationSet__KeyAssembler) BeginList(sizeHint int) (ipld.ListAssembler, error) {
	return mixins.StringAssembler{"types.MinerV0ExpirationSet.KeyAssembler"}.BeginList(0)
}
func (na *_MinerV0ExpirationSet__KeyAssembler) AssignNull() error {
	return mixins.StringAssembler{"types.MinerV0ExpirationSet.KeyAssembler"}.AssignNull()
}
func (_MinerV0ExpirationSet__KeyAssembler) AssignBool(bool) error {
	return mixins.StringAssembler{"types.MinerV0ExpirationSet.KeyAssembler"}.AssignBool(false)
}
func (_MinerV0ExpirationSet__KeyAssembler) AssignInt(int) error {
	return mixins.StringAssembler{"types.MinerV0ExpirationSet.KeyAssembler"}.AssignInt(0)
}
func (_MinerV0ExpirationSet__KeyAssembler) AssignFloat(float64) error {
	return mixins.StringAssembler{"types.MinerV0ExpirationSet.KeyAssembler"}.AssignFloat(0)
}
func (ka *_MinerV0ExpirationSet__KeyAssembler) AssignString(k string) error {
	if ka.state != maState_midKey {
		panic("misuse: KeyAssembler held beyond its valid lifetime")
	}
	switch k {
	case "OnTimeSectors":
		if ka.s & fieldBit__MinerV0ExpirationSet_OnTimeSectors != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MinerV0ExpirationSet_OnTimeSectors}
		}
		ka.s += fieldBit__MinerV0ExpirationSet_OnTimeSectors
		ka.state = maState_expectValue
		ka.f = 0
	case "EarlySectors":
		if ka.s & fieldBit__MinerV0ExpirationSet_EarlySectors != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MinerV0ExpirationSet_EarlySectors}
		}
		ka.s += fieldBit__MinerV0ExpirationSet_EarlySectors
		ka.state = maState_expectValue
		ka.f = 1
	case "OnTimePledge":
		if ka.s & fieldBit__MinerV0ExpirationSet_OnTimePledge != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MinerV0ExpirationSet_OnTimePledge}
		}
		ka.s += fieldBit__MinerV0ExpirationSet_OnTimePledge
		ka.state = maState_expectValue
		ka.f = 2
	case "ActivePower":
		if ka.s & fieldBit__MinerV0ExpirationSet_ActivePower != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MinerV0ExpirationSet_ActivePower}
		}
		ka.s += fieldBit__MinerV0ExpirationSet_ActivePower
		ka.state = maState_expectValue
		ka.f = 3
	case "FaultyPower":
		if ka.s & fieldBit__MinerV0ExpirationSet_FaultyPower != 0 {
			return ipld.ErrRepeatedMapKey{&fieldName__MinerV0ExpirationSet_FaultyPower}
		}
		ka.s += fieldBit__MinerV0ExpirationSet_FaultyPower
		ka.state = maState_expectValue
		ka.f = 4
	default:
		return ipld.ErrInvalidKey{TypeName:"types.MinerV0ExpirationSet", Key:&_String{k}}
	}
	return nil
}
func (_MinerV0ExpirationSet__KeyAssembler) AssignBytes([]byte) error {
	return mixins.StringAssembler{"types.MinerV0ExpirationSet.KeyAssembler"}.AssignBytes(nil)
}
func (_MinerV0ExpirationSet__KeyAssembler) AssignLink(ipld.Link) error {
	return mixins.StringAssembler{"types.MinerV0ExpirationSet.KeyAssembler"}.AssignLink(nil)
}
func (ka *_MinerV0ExpirationSet__KeyAssembler) AssignNode(v ipld.Node) error {
	if v2, err := v.AsString(); err != nil {
		return err
	} else {
		return ka.AssignString(v2)
	}
}
func (_MinerV0ExpirationSet__KeyAssembler) Prototype() ipld.NodePrototype {
	return _String__Prototype{}
}
func (MinerV0ExpirationSet) Type() schema.Type {
	return nil /*TODO:typelit*/
}
func (n MinerV0ExpirationSet) Representation() ipld.Node {
	return (*_MinerV0ExpirationSet__Repr)(n)
}
type _MinerV0ExpirationSet__Repr _MinerV0ExpirationSet
var _ ipld.Node = &_MinerV0ExpirationSet__Repr{}
func (_MinerV0ExpirationSet__Repr) ReprKind() ipld.ReprKind {
	return ipld.ReprKind_List
}
func (_MinerV0ExpirationSet__Repr) LookupByString(string) (ipld.Node, error) {
	return mixins.List{"types.MinerV0ExpirationSet.Repr"}.LookupByString("")
}
func (n *_MinerV0ExpirationSet__Repr) LookupByNode(key ipld.Node) (ipld.Node, error) {
	ki, err := key.AsInt()
	if err != nil {
		return nil, err
	}
	return n.LookupByIndex(ki)
}
func (n *_MinerV0ExpirationSet__Repr) LookupByIndex(idx int) (ipld.Node, error) {
	switch idx {
	case 0:
		return n.OnTimeSectors.Representation(), nil
	case 1:
		return n.EarlySectors.Representation(), nil
	case 2:
		return n.OnTimePledge.Representation(), nil
	case 3:
		return n.ActivePower.Representation(), nil
	case 4:
		return n.FaultyPower.Representation(), nil
	default:
		return nil, schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(idx)}
	}
}
func (n _MinerV0ExpirationSet__Repr) LookupBySegment(seg ipld.PathSegment) (ipld.Node, error) {
	i, err := seg.Index()
	if err != nil {
		return nil, ipld.ErrInvalidSegmentForList{TypeName: "types.MinerV0ExpirationSet.Repr", TroubleSegment: seg, Reason: err}
	}
	return n.LookupByIndex(i)
}
func (_MinerV0ExpirationSet__Repr) MapIterator() ipld.MapIterator {
	return nil
}
func (n *_MinerV0ExpirationSet__Repr) ListIterator() ipld.ListIterator {
	return &_MinerV0ExpirationSet__ReprListItr{n, 0}
}

type _MinerV0ExpirationSet__ReprListItr struct {
	n   *_MinerV0ExpirationSet__Repr
	idx int
	
}

func (itr *_MinerV0ExpirationSet__ReprListItr) Next() (idx int, v ipld.Node, err error) {
	if itr.idx >= 5 {
		return -1, nil, ipld.ErrIteratorOverread{}
	}
	switch itr.idx {
	case 0:
		idx = itr.idx
		v = itr.n.OnTimeSectors.Representation()
	case 1:
		idx = itr.idx
		v = itr.n.EarlySectors.Representation()
	case 2:
		idx = itr.idx
		v = itr.n.OnTimePledge.Representation()
	case 3:
		idx = itr.idx
		v = itr.n.ActivePower.Representation()
	case 4:
		idx = itr.idx
		v = itr.n.FaultyPower.Representation()
	default:
		panic("unreachable")
	}
	itr.idx++
	return
}
func (itr *_MinerV0ExpirationSet__ReprListItr) Done() bool {
	return itr.idx >= 5
}

func (rn *_MinerV0ExpirationSet__Repr) Length() int {
	l := 5
	return l
}
func (_MinerV0ExpirationSet__Repr) IsAbsent() bool {
	return false
}
func (_MinerV0ExpirationSet__Repr) IsNull() bool {
	return false
}
func (_MinerV0ExpirationSet__Repr) AsBool() (bool, error) {
	return mixins.List{"types.MinerV0ExpirationSet.Repr"}.AsBool()
}
func (_MinerV0ExpirationSet__Repr) AsInt() (int, error) {
	return mixins.List{"types.MinerV0ExpirationSet.Repr"}.AsInt()
}
func (_MinerV0ExpirationSet__Repr) AsFloat() (float64, error) {
	return mixins.List{"types.MinerV0ExpirationSet.Repr"}.AsFloat()
}
func (_MinerV0ExpirationSet__Repr) AsString() (string, error) {
	return mixins.List{"types.MinerV0ExpirationSet.Repr"}.AsString()
}
func (_MinerV0ExpirationSet__Repr) AsBytes() ([]byte, error) {
	return mixins.List{"types.MinerV0ExpirationSet.Repr"}.AsBytes()
}
func (_MinerV0ExpirationSet__Repr) AsLink() (ipld.Link, error) {
	return mixins.List{"types.MinerV0ExpirationSet.Repr"}.AsLink()
}
func (_MinerV0ExpirationSet__Repr) Prototype() ipld.NodePrototype {
	return _MinerV0ExpirationSet__ReprPrototype{}
}
type _MinerV0ExpirationSet__ReprPrototype struct{}

func (_MinerV0ExpirationSet__ReprPrototype) NewBuilder() ipld.NodeBuilder {
	var nb _MinerV0ExpirationSet__ReprBuilder
	nb.Reset()
	return &nb
}
type _MinerV0ExpirationSet__ReprBuilder struct {
	_MinerV0ExpirationSet__ReprAssembler
}
func (nb *_MinerV0ExpirationSet__ReprBuilder) Build() ipld.Node {
	if *nb.m != schema.Maybe_Value {
		panic("invalid state: cannot call Build on an assembler that's not finished")
	}
	return nb.w
}
func (nb *_MinerV0ExpirationSet__ReprBuilder) Reset() {
	var w _MinerV0ExpirationSet
	var m schema.Maybe
	*nb = _MinerV0ExpirationSet__ReprBuilder{_MinerV0ExpirationSet__ReprAssembler{w: &w, m: &m}}
}
type _MinerV0ExpirationSet__ReprAssembler struct {
	w *_MinerV0ExpirationSet
	m *schema.Maybe
	state laState
	f int

	cm schema.Maybe
	ca_OnTimeSectors _BitField__ReprAssembler
	ca_EarlySectors _BitField__ReprAssembler
	ca_OnTimePledge _BigInt__ReprAssembler
	ca_ActivePower _MinerV0PowerPair__ReprAssembler
	ca_FaultyPower _MinerV0PowerPair__ReprAssembler
	}

func (na *_MinerV0ExpirationSet__ReprAssembler) reset() {
	na.state = laState_initial
	na.f = 0
	na.ca_OnTimeSectors.reset()
	na.ca_EarlySectors.reset()
	na.ca_OnTimePledge.reset()
	na.ca_ActivePower.reset()
	na.ca_FaultyPower.reset()
}
func (_MinerV0ExpirationSet__ReprAssembler) BeginMap(sizeHint int) (ipld.MapAssembler, error) {
	return mixins.ListAssembler{"types.MinerV0ExpirationSet.Repr"}.BeginMap(0)
}
func (na *_MinerV0ExpirationSet__ReprAssembler) BeginList(int) (ipld.ListAssembler, error) {
	switch *na.m {
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: it makes no sense to 'begin' twice on the same assembler!")
	}
	*na.m = midvalue
	if na.w == nil {
		na.w = &_MinerV0ExpirationSet{}
	}
	return na, nil
}
func (na *_MinerV0ExpirationSet__ReprAssembler) AssignNull() error {
	switch *na.m {
	case allowNull:
		*na.m = schema.Maybe_Null
		return nil
	case schema.Maybe_Absent:
		return mixins.ListAssembler{"types.MinerV0ExpirationSet.Repr.Repr"}.AssignNull()
	case schema.Maybe_Value, schema.Maybe_Null:
		panic("invalid state: cannot assign into assembler that's already finished")
	case midvalue:
		panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
	}
	panic("unreachable")
}
func (_MinerV0ExpirationSet__ReprAssembler) AssignBool(bool) error {
	return mixins.ListAssembler{"types.MinerV0ExpirationSet.Repr"}.AssignBool(false)
}
func (_MinerV0ExpirationSet__ReprAssembler) AssignInt(int) error {
	return mixins.ListAssembler{"types.MinerV0ExpirationSet.Repr"}.AssignInt(0)
}
func (_MinerV0ExpirationSet__ReprAssembler) AssignFloat(float64) error {
	return mixins.ListAssembler{"types.MinerV0ExpirationSet.Repr"}.AssignFloat(0)
}
func (_MinerV0ExpirationSet__ReprAssembler) AssignString(string) error {
	return mixins.ListAssembler{"types.MinerV0ExpirationSet.Repr"}.AssignString("")
}
func (_MinerV0ExpirationSet__ReprAssembler) AssignBytes([]byte) error {
	return mixins.ListAssembler{"types.MinerV0ExpirationSet.Repr"}.AssignBytes(nil)
}
func (_MinerV0ExpirationSet__ReprAssembler) AssignLink(ipld.Link) error {
	return mixins.ListAssembler{"types.MinerV0ExpirationSet.Repr"}.AssignLink(nil)
}
func (na *_MinerV0ExpirationSet__ReprAssembler) AssignNode(v ipld.Node) error {
	if v.IsNull() {
		return na.AssignNull()
	}
	if v2, ok := v.(*_MinerV0ExpirationSet); ok {
		switch *na.m {
		case schema.Maybe_Value, schema.Maybe_Null:
			panic("invalid state: cannot assign into assembler that's already finished")
		case midvalue:
			panic("invalid state: cannot assign null into an assembler that's already begun working on recursive structures!")
		}
		if na.w == nil {
			na.w = v2
			*na.m = schema.Maybe_Value
			return nil
		}
		*na.w = *v2
		*na.m = schema.Maybe_Value
		return nil
	}
	if v.ReprKind() != ipld.ReprKind_List {
		return ipld.ErrWrongKind{TypeName: "types.MinerV0ExpirationSet.Repr", MethodName: "AssignNode", AppropriateKind: ipld.ReprKindSet_JustList, ActualKind: v.ReprKind()}
	}
	itr := v.ListIterator()
	for !itr.Done() {
		_, v, err := itr.Next()
		if err != nil {
			return err
		}
		if err := na.AssembleValue().AssignNode(v); err != nil {
			return err
		}
	}
	return na.Finish()
}
func (_MinerV0ExpirationSet__ReprAssembler) Prototype() ipld.NodePrototype {
	return _MinerV0ExpirationSet__ReprPrototype{}
}
func (la *_MinerV0ExpirationSet__ReprAssembler) valueFinishTidy() bool {
	switch la.f {
	case 0:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 1:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 2:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 3:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	case 4:
		switch la.cm {
		case schema.Maybe_Value:
			la.cm = schema.Maybe_Absent
			la.state = laState_initial
			la.f++
			return true
		default:
			return false
		}
	default:
		panic("unreachable")
	}
}
func (la *_MinerV0ExpirationSet__ReprAssembler) AssembleValue() ipld.NodeAssembler {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: AssembleValue cannot be called when still in the middle of assembling the previous value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: AssembleValue cannot be called on an assembler that's already finished")
	}
	if la.f >= 5 {
		return nil // schema.ErrNoSuchField{Type: nil /*TODO*/, Field: ipld.PathSegmentOfInt(5)} // FIXME: need an error thunking assembler!  it has returned.  sigh.
	}
	la.state = laState_midValue
	switch la.f {
	case 0:
		la.ca_OnTimeSectors.w = &la.w.OnTimeSectors
		la.ca_OnTimeSectors.m = &la.cm
		return &la.ca_OnTimeSectors
	case 1:
		la.ca_EarlySectors.w = &la.w.EarlySectors
		la.ca_EarlySectors.m = &la.cm
		return &la.ca_EarlySectors
	case 2:
		la.ca_OnTimePledge.w = &la.w.OnTimePledge
		la.ca_OnTimePledge.m = &la.cm
		return &la.ca_OnTimePledge
	case 3:
		la.ca_ActivePower.w = &la.w.ActivePower
		la.ca_ActivePower.m = &la.cm
		return &la.ca_ActivePower
	case 4:
		la.ca_FaultyPower.w = &la.w.FaultyPower
		la.ca_FaultyPower.m = &la.cm
		return &la.ca_FaultyPower
	default:
		panic("unreachable")
	}
}
func (la *_MinerV0ExpirationSet__ReprAssembler) Finish() error {
	switch la.state {
	case laState_initial:
		// carry on
	case laState_midValue:
		if !la.valueFinishTidy() {
			panic("invalid state: Finish cannot be called when in the middle of assembling a value")
		} // if tidy success: carry on
	case laState_finished:
		panic("invalid state: Finish cannot be called on an assembler that's already finished")
	}
	la.state = laState_finished
	*la.m = schema.Maybe_Value
	return nil
}
func (la *_MinerV0ExpirationSet__ReprAssembler) ValuePrototype(_ int) ipld.NodePrototype {
	panic("todo structbuilder tuplerepr valueprototype")
}
