name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.14
      id: go

    - name: Set up Node
      uses: actions/setup-node@v3.8.1
      with:
        node-version: '12'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get github.com/go-bindata/go-bindata/go-bindata
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        go generate ./...
        go build -v ./cmd/statediff
        go build -v ./cmd/stateexplorer
        go build -v ./cmd/statedump
        go build -v ./cmd/stateql

    - name: Test
      run: go test -v ./...
